import {
  analyzeImportedConnectionGeometry,
  importedConnectionBoxesTouch,
  type ImportedConnectionItem,
  type ImportedConnectionNode,
  type ImportedConnectionProfile,
  type ImportedConnectionVector,
} from './importedConnectionGeometry';
import type { ImportedSourceMesh } from './importedSourceMesh';
import { describeImportedNo1Hardware, type ImportedConnectionHardware } from './importedConnectionHardware';

type Vec3 = ImportedConnectionVector;
export interface ImportedConnectionSceneItem extends ImportedConnectionItem {
  kind: string;
  variantId?: string;
  length?: number;
  width?: number;
  height?: number;
  thickness?: number;
  autoGenerated?: boolean;
  lockedPosition?: boolean;
  attachedPartIds?: string[];
  importedConnectionDraft?: unknown;
}
export interface ImportedConnectionBox {
  position: Vec3;
  axes: [Vec3, Vec3, Vec3];
  halfSizes: Vec3;
}
export interface ImportedNativeProfileProxy {
  id: string;
  kind: 'profile';
  name: string;
  variantId: string;
  length: number;
  position: Vec3;
  rotation: Vec3;
  colorId: string;
  quantity: number;
}
export interface ImportedConnectionMachiningSuggestion {
  profileId: string;
  holes?: unknown[];
  tappingLeft?: boolean;
  tappingRight?: boolean;
  description?: string;
}
export interface ImportedNativeConnectionRequest {
  profiles: ImportedNativeProfileProxy[];
  existingItems: readonly ImportedConnectionSceneItem[];
  memberIds: [string, string];
  jointKey: string;
  pointMm: Vec3;
  geometryNode: ImportedConnectionNode;
}
export interface ImportedNativeConnectionOption<T extends ImportedConnectionSceneItem = ImportedConnectionSceneItem> {
  items: T[];
  method?: 'corner_bracket' | 'slot_connector';
  /** Real connector body/seat envelopes in world millimetres, not entire joint boxes. */
  occupiedBoxesMm?: ImportedConnectionBox[];
  /** Advice only: these operations are never inserted into the source geometry. */
  machining?: ImportedConnectionMachiningSuggestion[];
  issues?: string[];
}
export interface ImportedNativeConnectionSuggestion<T extends ImportedConnectionSceneItem = ImportedConnectionSceneItem>
  extends ImportedNativeConnectionOption<T> {
  alternatives?: ImportedNativeConnectionOption<T>[];
}
export interface ImportedConnectionMemberPose {
  id: string;
  position: Vec3;
  rotation: Vec3;
  sourceFileSha256: string;
  sourceInstancePath: string;
  sourceGeometryFingerprint: string;
}
export interface ImportedConnectionPartPose {
  position: Vec3;
  rotation: Vec3;
  kind: string;
  variantId?: string;
  length?: number;
  width?: number;
  height?: number;
  thickness?: number;
  accessoryProfileSize?: string | number;
  accessoryThreadSize?: string | number;
  catalogItemId?: string;
  fastenerCatalogId?: string;
  shelfSupportType?: string;
  colorId?: string;
}
export interface ImportedConnectionDraft {
  schemaVersion: 1;
  jointKey: string;
  memberIds: [string, string];
  memberPoses: ImportedConnectionMemberPose[];
  partPose: ImportedConnectionPartPose;
  method: 'corner_bracket' | 'slot_connector';
  reviewStatus: 'needs_review';
  machining?: ImportedConnectionMachiningSuggestion[];
  /** Candidate body envelopes, advisory only; rescans recalculate them. */
  occupiedBoxesMm?: ImportedConnectionBox[];
  hardware?: ImportedConnectionHardware;
}
export interface ImportedConnectionPlanNode<T extends ImportedConnectionSceneItem = ImportedConnectionSceneItem> {
  id: string;
  memberIds: string[];
  pointMm: Vec3;
  status: 'proposed' | 'existing' | 'review';
  reason: string;
  issues: string[];
  existingSourceAccessoryIds: string[];
  existingDraftIds: string[];
  previewItems: T[];
  machining: ImportedConnectionMachiningSuggestion[];
  sourceAccessoryRelations?: ImportedConnectionNode['sourceAccessoryRelations'];
}
export interface ImportedConnectionPlan<T extends ImportedConnectionSceneItem = ImportedConnectionSceneItem> {
  sourceSignature: string;
  profiles: ImportedConnectionProfile[];
  nodes: ImportedConnectionPlanNode<T>[];
  previewItems: T[];
  summary: {
    profileCount: number;
    eligibleProfileCount: number;
    nodeCount: number;
    proposedCount: number;
    existingCount: number;
    reviewCount: number;
    addedAccessoryCount: number;
    machiningSuggestionCount: number;
  };
}

const record = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const vec = (value?: readonly number[]): Vec3 => value?.length === 3 && value.every(Number.isFinite)
  ? [value[0], value[1], value[2]] : [0, 0, 0];
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const canonical = (value: unknown): unknown => Array.isArray(value) ? value.map(canonical)
  : record(value) ? Object.fromEntries(Object.keys(value).sort().filter((key) => value[key] !== undefined).map((key) => [key, canonical(value[key])])) : value;
const sameEvidence = (a: unknown, b: unknown) => JSON.stringify(canonical(a)) === JSON.stringify(canonical(b));
const hashText = (text: string) => {
  let value = 2166136261;
  for (let i = 0; i < text.length; i += 1) value = Math.imul(value ^ text.charCodeAt(i), 16777619);
  return (value >>> 0).toString(16).padStart(8, '0');
};
// A source mesh is immutable in the editor. Pose edits retain its reference; a
// replacement mesh gets a new revision even when it repeats the same source ID.
const fingerprints = new WeakMap<ImportedSourceMesh, { revision: number; fingerprint: string }>();
let meshRevision = 0;
function meshIdentity(mesh: ImportedSourceMesh) {
  const cached = fingerprints.get(mesh); if (cached) return cached;
  let hash = 2166136261;
  const scratch = new DataView(new ArrayBuffer(8));
  for (const array of [mesh.positionsMm, mesh.indices, mesh.normals || [], mesh.uvs || []]) {
    hash = Math.imul(hash ^ array.length, 16777619);
    for (const value of array) {
      scratch.setFloat64(0, value, true);
      hash = Math.imul(hash ^ scratch.getUint32(0, true), 16777619);
      hash = Math.imul(hash ^ scratch.getUint32(4, true), 16777619);
    }
  }
  const fingerprint = `${(hash >>> 0).toString(16)}:${hashText(JSON.stringify([mesh.groups, mesh.materials.map((material) => ({
    ...material, texture: material.texture ? { mimeType: material.texture.mimeType, content: hashText(material.texture.base64) } : undefined,
  }))]))}`;
  const result = { revision: ++meshRevision, fingerprint }; fingerprints.set(mesh, result); return result;
}

/** Local preview revision; never an approval, signature or source-file checksum. */
export function importedConnectionSceneSignature(items: readonly ImportedConnectionSceneItem[]): string {
  const evidence = items.map((item) => {
    const { sourceMesh, ...fields } = item;
    return [fields, sourceMesh ? [meshIdentity(sourceMesh), sourceMesh.source, sourceMesh.boundsMm] : null];
  });
  return hashText(JSON.stringify(evidence));
}

const partPose = (item: ImportedConnectionSceneItem): ImportedConnectionPartPose => ({
  position: vec(item.position), rotation: vec(item.rotation), kind: item.kind,
  ...Object.fromEntries(['variantId', 'length', 'width', 'height', 'thickness', 'accessoryProfileSize', 'accessoryThreadSize',
    'catalogItemId', 'fastenerCatalogId', 'shelfSupportType', 'colorId'].flatMap((key) => {
    const value = (item as unknown as Record<string, unknown>)[key]; return value === undefined ? [] : [[key, value]];
  })),
});
function memberPose(item: ImportedConnectionSceneItem): ImportedConnectionMemberPose {
  return { id: item.id, position: vec(item.position), rotation: vec(item.rotation),
    sourceFileSha256: item.sourceMesh?.source.fileSha256 || '', sourceInstancePath: item.sourceMesh?.source.instancePath || '',
    sourceGeometryFingerprint: item.sourceMesh ? `${meshIdentity(item.sourceMesh).fingerprint}:${hashText(JSON.stringify(canonical([
      item.sourceMesh.source, item.sourceMesh.boundsMm,
    ])))}` : '' };
}

/** Kept separate from manufacturing checks: every draft remains needs_review. */
export function inspectImportedConnectionDraft(item: ImportedConnectionSceneItem, items: readonly ImportedConnectionSceneItem[]): string[] {
  const draft = item.importedConnectionDraft;
  if (!record(draft)) return ['连接草稿记录缺失或损坏。'];
  const issues: string[] = [];
  if (draft.schemaVersion !== 1 || draft.reviewStatus !== 'needs_review') issues.push('连接草稿版本或待核标记不正确。');
  if (!Array.isArray(draft.memberIds) || draft.memberIds.length !== 2 || draft.memberIds.some((id) => typeof id !== 'string')
    || new Set(draft.memberIds).size !== 2 || draft.jointKey !== [...draft.memberIds].sort().join(':JOINT:')) issues.push('连接草稿关联节点不正确。');
  const savedPoses = Array.isArray(draft.memberPoses) ? draft.memberPoses : [];
  if (savedPoses.length !== 2) issues.push('连接草稿缺少源构件位姿记录。');
  if (savedPoses.some((pose) => !record(pose) || !Array.isArray(draft.memberIds) || !draft.memberIds.includes(pose.id))
    || new Set(savedPoses.map((pose) => record(pose) ? pose.id : undefined)).size !== savedPoses.length) issues.push('连接草稿父构件位姿与关联不匹配。');
  for (const saved of savedPoses) {
    const current = record(saved) && items.find((candidate) => candidate.id === saved.id);
    if (!current?.sourceMesh) { issues.push('关联源构件已删除或替换，需要重新核对连接。'); continue; }
    if (!sameEvidence(saved, memberPose(current))) issues.push('源构件位置、旋转或几何已改变，需要重新核对连接。');
  }
  if (!sameEvidence(draft.partPose, partPose(item))) issues.push('连接件位置、旋转或规格已改变，需要重新核对连接。');
  if ((item as unknown as { quantity?: number }).quantity !== undefined && (item as unknown as { quantity?: number }).quantity !== 1) {
    issues.push('每个连接草稿只代表一个实物接点，数量不是1时需拆分实例后重新核对。');
  }
  return [...new Set(issues)];
}

const validBox = (box: ImportedConnectionBox) => box && Array.isArray(box.axes) && box.axes.length === 3
  && [box.position, box.halfSizes, ...box.axes].every((v) => (
  Array.isArray(v) && v.length === 3 && v.every(Number.isFinite)
)) && box.halfSizes.every((n) => n >= 0) && box.axes.every((axis) => Math.abs(Math.hypot(...axis) - 1) < 1e-4)
  && Math.abs(box.axes[0].reduce((sum, n, i) => sum + n * box.axes[1][i], 0)) < 1e-4
  && Math.abs(box.axes[0].reduce((sum, n, i) => sum + n * box.axes[2][i], 0)) < 1e-4
  && Math.abs(box.axes[1].reduce((sum, n, i) => sum + n * box.axes[2][i], 0)) < 1e-4;
const draftJoint = (item: ImportedConnectionSceneItem) => record(item.importedConnectionDraft)
  && typeof item.importedConnectionDraft.jointKey === 'string' ? item.importedConnectionDraft.jointKey : null;

/** Upgrade the advisory checklist on older drafts without altering any geometry. */
export function withImportedConnectionHardware<T extends ImportedConnectionSceneItem>(items: readonly T[]): T[] {
  return items.map((item) => {
    const marker = item.importedConnectionDraft;
    if (!record(marker) || marker.method !== 'corner_bracket' || marker.hardware !== undefined) return item;
    const hardware = describeImportedNo1Hardware(item);
    return hardware ? { ...item, importedConnectionDraft: { ...marker, hardware } } : item;
  });
}

function sameHardwarePlacement(a: ImportedConnectionSceneItem, b: ImportedConnectionSceneItem): boolean {
  const left = partPose(a); const right = partPose(b);
  if (!left.position.every((value, i) => Math.abs(value - right.position[i]) < 0.001)
    || !left.rotation.every((value, i) => Math.abs(value - right.rotation[i]) < 0.001)) return false;
  return sameEvidence({ ...left, position: [], rotation: [] }, { ...right, position: [], rotation: [] });
}

export function createImportedConnectionPlan<T extends ImportedConnectionSceneItem>(
  source: readonly T[],
  nativePlanner: (request: ImportedNativeConnectionRequest) => ImportedNativeConnectionSuggestion<T>,
): ImportedConnectionPlan<T> {
  if (new Set(source.map((item) => item.id)).size !== source.length) throw new Error('构件 ID 重复，不能生成连接草稿。');
  const sourceSignature = importedConnectionSceneSignature(source);
  const geometry = analyzeImportedConnectionGeometry(source);
  const profiles: ImportedNativeProfileProxy[] = geometry.profiles.filter((profile) => profile.geometryVerified && profile.visible).map((profile) => ({
    id: profile.id, kind: 'profile', name: `源型材代理 ${profile.variantId}`, variantId: profile.variantId, length: profile.lengthMm,
    position: [...profile.position], rotation: [...profile.rotation], colorId: 'natural', quantity: 1,
  }));
  const byId = new Map(source.map((item) => [item.id, item]));
  const chosenBoxes: ImportedConnectionBox[] = [];
  const usedIds = new Set(source.map((item) => item.id));
  const nodes: ImportedConnectionPlanNode<T>[] = [];
  for (const original of geometry.nodes) {
    const existingDrafts = source.filter((item) => draftJoint(item) === original.id);
    const node: ImportedConnectionPlanNode<T> = { ...original, status: original.status === 'candidate' ? 'review' : original.status,
      issues: [...original.issues], existingDraftIds: existingDrafts.map((item) => item.id), previewItems: [], machining: [] };
    nodes.push(node);
    if (existingDrafts.length) {
      const issues = existingDrafts.flatMap((item) => inspectImportedConnectionDraft(item, source));
      // A board or another piece of hardware may move into a formerly clear
      // seat without changing either parent. Recalculate the same seat; never
      // relocate or replace an already-added fitting as a side effect of scan.
      if (!issues.length && original.memberIds.length === 2) {
        try {
          const ownIds = new Set(existingDrafts.map((item) => item.id));
          const proposal = nativePlanner({ profiles: clone(profiles), existingItems: source.filter((item) => !ownIds.has(item.id)),
            memberIds: original.memberIds as [string, string], jointKey: original.id,
            pointMm: [...original.pointMm], geometryNode: clone(original) });
          const option = [proposal, ...(proposal.alternatives || [])].find((candidate) => candidate.items.length === existingDrafts.length
            && existingDrafts.every((item) => candidate.items.some((part) => sameHardwarePlacement(item, part))));
          const boxes = option?.occupiedBoxesMm;
          if (!boxes?.length || !boxes.every(validBox)) issues.push('原配件位置无法通过当前连接规则复查；保留配件，请核对周围板件、五金及安装方向。');
          else {
            const sourceBlockers: ImportedConnectionBox[] = [...geometry.obstacles.filter((part) => !part.referenceOnly),
              ...geometry.profiles.filter((part) => part.visible && !original.memberIds.includes(part.id))];
            if (boxes.some((box) => sourceBlockers.some((obstacle) => importedConnectionBoxesTouch(box, obstacle, -0.05)))) {
              issues.push('原配件包络与当前板件、其他型材或配件相交；未自动挪动，请调整后重新扫描。');
            }
            if (boxes.some((box) => chosenBoxes.some((obstacle) => importedConnectionBoxesTouch(box, obstacle, -0.05)))) {
              issues.push('该配件与其他连接方案的包络相交，请核对相邻接点。');
            }
            chosenBoxes.push(...clone(boxes));
          }
        } catch { issues.push('现有配件的周边复查未完成，保留原位并待核。'); }
      }
      node.status = issues.length ? 'review' : 'existing';
      node.issues.push(...issues);
      node.reason = issues.length ? [...new Set(issues)].join(' ') : '已添加连接件草稿，连接座面、紧固件及安装仍需核对。';
      continue;
    }
    if (original.status !== 'candidate' || original.memberIds.length !== 2) continue;
    const members = original.memberIds as [string, string];
    const blockers: ImportedConnectionBox[] = [
      ...geometry.obstacles.filter((part) => !part.referenceOnly),
      ...geometry.profiles.filter((part) => part.visible && !members.includes(part.id)),
      ...chosenBoxes,
    ];
    let proposal: ImportedNativeConnectionSuggestion<T>;
    try {
      proposal = nativePlanner({ profiles: clone(profiles), existingItems: source, memberIds: [...members],
        jointKey: original.id, pointMm: [...original.pointMm], geometryNode: clone(original) });
    } catch (error) {
      node.issues.push(`该接点的原生连接规则未能完成：${error instanceof Error ? error.message : '未知错误'}`);
      node.reason = node.issues.join(' '); continue;
    }
    const attempts = [proposal, ...(proposal.alternatives || [])];
    const failures: string[] = [];
    let accepted = false;
    for (const option of attempts) {
      const machining = (option.machining || []).filter((suggestion) => members.includes(suggestion.profileId));
      if (!node.machining.length) node.machining = clone(machining);
      if (!option.items?.length) { failures.push(...(option.issues || [])); continue; }
      if (option.items.some((item) => !['connector', 'hidden_connector'].includes(item.kind) || item.sourceMesh)) {
        failures.push('候选中含非连接配件或源几何；不会添加代理型材、假孔或挂孔螺丝。'); continue;
      }
      const boxes = option.occupiedBoxesMm;
      if (!boxes?.length || !boxes.every(validBox)) { failures.push('候选配件缺少有效的真实包络，需人工定位。'); continue; }
      // A tiny penetration allowance avoids counting an exact mating face as
      // an obstruction. This is conservative OBB exclusion, not solid clearance.
      if (boxes.some((box) => blockers.some((obstacle) => importedConnectionBoxesTouch(box, obstacle, -0.05)))) {
        failures.push('候选配件包络与板件、其他型材或配件相交，需人工核对或改换方向。'); continue;
      }
      const snapshots = members.map((id) => memberPose(byId.get(id)!));
      const method = option.method || (option.items.some((item) => item.kind === 'hidden_connector') ? 'slot_connector' : 'corner_bracket');
      node.previewItems = option.items.map((candidate, index) => {
        const body = clone(candidate) as T & Record<string, unknown>;
        const baseId = `imported-connection-${hashText(original.id)}-${index + 1}`;
        let id = baseId; let suffix = 1; while (usedIds.has(id)) id = `${baseId}-${++suffix}`;
        usedIds.add(id);
        for (const key of ['linkedProfileId', 'linkedHoleId', 'attachmentKey', 'attachedProfileIds', 'holes', 'tappingLeft', 'tappingRight',
          'autoConnectionTappingLeft', 'autoConnectionTappingRight', 'no5Validation']) delete body[key];
        body.id = id; body.autoGenerated = false; body.lockedPosition = false; body.attachedPartIds = [...members];
        const hardware = describeImportedNo1Hardware(body);
        body.importedConnectionDraft = { schemaVersion: 1, jointKey: original.id, memberIds: [...members], memberPoses: clone(snapshots),
          partPose: partPose(body), method, reviewStatus: 'needs_review', occupiedBoxesMm: clone(boxes), ...(hardware ? { hardware } : {}), ...(machining.length ? { machining: clone(machining) } : {}) } satisfies ImportedConnectionDraft;
        return body;
      });
      node.machining = clone(machining); node.status = 'proposed';
      node.issues.push(...(option.issues || []));
      node.reason = '可添加真实目录连接件草稿；源网格不改孔，紧固件、槽位与安装仍待核。';
      chosenBoxes.push(...clone(boxes)); accepted = true; break;
    }
    if (!accepted) { node.issues.push(...new Set(failures)); node.reason = node.issues.join(' ') || '没有通过本节点保守检查的配件候选，保留源几何待核。'; }
  }
  // A detached/moved draft must not disappear from the report merely because
  // its former two members are no longer touching or have been deleted.
  for (const item of source.filter((part) => part.importedConnectionDraft !== undefined)) {
    const key = draftJoint(item); if (key && nodes.some((node) => node.id === key)) continue;
    const issues = inspectImportedConnectionDraft(item, source);
    const marker = record(item.importedConnectionDraft) ? item.importedConnectionDraft : {};
    nodes.push({ id: key || `invalid-draft:${item.id}`, memberIds: Array.isArray(marker.memberIds) ? marker.memberIds.filter((id): id is string => typeof id === 'string') : [],
      pointMm: vec(item.position), status: 'review', reason: '已有连接草稿的接点不再匹配，保留配件并重新核对。',
      issues, existingSourceAccessoryIds: [], existingDraftIds: [item.id], previewItems: [], machining: [] });
  }
  if (importedConnectionSceneSignature(source) !== sourceSignature) throw new Error('扫描期间场景已改变，请重新扫描连接。');
  const previewItems = nodes.flatMap((node) => node.previewItems);
  return { sourceSignature, profiles: geometry.profiles, nodes, previewItems, summary: {
    profileCount: geometry.profiles.length, eligibleProfileCount: geometry.profiles.filter((profile) => profile.eligibleForNative).length,
    nodeCount: nodes.length, proposedCount: nodes.filter((node) => node.status === 'proposed').length,
    existingCount: nodes.filter((node) => node.status === 'existing').length, reviewCount: nodes.filter((node) => node.status === 'review').length,
    addedAccessoryCount: previewItems.length, machiningSuggestionCount: nodes.reduce((sum, node) => sum + node.machining.length, 0),
  } };
}

/** Append-only transaction. Never replaces a source item or applies drilling. */
export function applyImportedConnectionPlan<T extends ImportedConnectionSceneItem>(
  source: readonly T[], plan: ImportedConnectionPlan<T>, selectedNodeIds?: readonly string[],
): { items: T[]; addedItems: T[]; appliedNodeIds: string[] } {
  // Reapplying the exact same transaction is a no-op; still verify that neither
  // the source nor the already-added draft parts were edited in the meantime.
  const plannedIds = new Set(plan.previewItems.map((item) => item.id));
  const base = source.filter((item) => !plannedIds.has(item.id));
  if (importedConnectionSceneSignature(base) !== plan.sourceSignature) throw new Error('连接预览已过期，场景或源几何发生变化；请重新扫描。');
  for (const existing of source.filter((item) => plannedIds.has(item.id))) {
    const planned = plan.previewItems.find((item) => item.id === existing.id);
    if (JSON.stringify(existing) !== JSON.stringify(planned)) throw new Error('已添加的连接件已改变，请重新扫描，不能覆盖现有配件。');
  }
  const selected = new Set(selectedNodeIds || plan.nodes.filter((node) => node.status === 'proposed').map((node) => node.id));
  if ([...selected].some((id) => !plan.nodes.some((node) => node.id === id && node.status === 'proposed'))) throw new Error('所选接点没有可添加的连接草稿。');
  const addedItems: T[] = []; const appliedNodeIds: string[] = [];
  for (const node of plan.nodes.filter((entry) => selected.has(entry.id))) {
    for (const item of node.previewItems) {
      const existing = source.find((part) => part.id === item.id);
      if (existing) {
        if (JSON.stringify(existing) !== JSON.stringify(item)) throw new Error('已添加的连接件已改变，请重新扫描，不能覆盖现有配件。');
        continue;
      }
      if (inspectImportedConnectionDraft(item, source).length) throw new Error('连接草稿与当前源构件不一致，请重新扫描。');
      addedItems.push(clone(item));
    }
    if (node.previewItems.some((item) => addedItems.some((added) => added.id === item.id))) appliedNodeIds.push(node.id);
  }
  return { items: [...source, ...addedItems], addedItems, appliedNodeIds };
}
