import type { DrillHole, ProfileFinish, ProfileSide } from '../types';

export type ParametricFurnitureSource = 'calligraphy_cabinet' | 'wardrobe';

export type ParametricItemKind =
  | 'profile'
  | 'marine_board'
  | 'shelf_support'
  | 'connector';

export type ParametricShelfSupportType = 'linear' | 'board_12mm';

export interface ParametricSceneItem {
  id: string;
  kind: ParametricItemKind;
  name: string;
  position: [number, number, number];
  rotation: [number, number, number];
  colorId: string;
  quantity: number;
  variantId?: string;
  length?: number;
  width?: number;
  height?: number;
  thickness?: number;
  holes?: DrillHole[];
  tappingLeft?: boolean;
  tappingRight?: boolean;
  finish?: ProfileFinish;
  shelfSupportType?: ParametricShelfSupportType;
  accessoryPrice?: number;
  accessoryProfileSize?: '2020';
  autoGenerated?: boolean;
  lockedPosition?: boolean;
  attachedProfileIds?: string[];
  attachmentKey?: string;
  remark?: string;
}

export interface ParametricTemplatePayload {
  schemaVersion: 1;
  source: ParametricFurnitureSource;
  createdAt: string;
  summary: Record<string, number | string>;
  items: ParametricSceneItem[];
}

export const DIY_TEMPLATE_STORAGE_PREFIX = 'mengkaile_diy_template_v1:';
export const MAX_FURNITURE_PROFILE_MM = 3000;

export const CALLIGRAPHY_BASKET_WIDTH_MM = 300;
export const CALLIGRAPHY_BASKET_DEPTH_MM = 420;
export const CALLIGRAPHY_BASKET_HEIGHT_MM = 100;
export const CALLIGRAPHY_LAYER_PITCH_MM = 130;
export const CALLIGRAPHY_OUTER_DEPTH_MM = 460;
export const CALLIGRAPHY_PROFILE_MM = 20;
export const CALLIGRAPHY_MAX_LENGTH_MM = 3000;
export const CALLIGRAPHY_MAX_HEIGHT_MM = 1600;
export const CALLIGRAPHY_TOP_BOARD_MAX_PIECE_MM = 2440;
export const WARDROBE_MIN_STORAGE_CLEARANCE_MM = 80;
export const WARDROBE_MAX_STORAGE_LAYERS = 20;
export const WARDROBE_MAX_COLUMNS = 9;
// Keep enough centre-to-centre space for the two No.1 brackets at the ends of
// every per-column front/rear rail. This is a collision-prevention limit, not
// a promise that every narrow bay is useful as a hanging compartment.
export const WARDROBE_MIN_COLUMN_PITCH_MM = 80;
// A 2040 wide face exposes two 20mm module grooves. Intermediate wardrobe
// shelf rails always use the groove facing the usable cabinet interior:
// front rails move toward -Z and rear rails toward +Z, independent of which
// physical side of the cabinet the customer is viewing.
export const WARDROBE_2040_INNER_GROOVE_OFFSET_MM = 10;
export const WARDROBE_12MM_BOARD_SUPPORT_PRICE = 0.7;

export const SHELF_SUPPORT_PRICE_PER_METER: Record<ProfileFinish, number> = {
  oxidized: 8,
  electrophoretic: 10,
  powder: 12,
};

export const getShelfSupportUnitPrice = (lengthMm: number, finish: ProfileFinish) => (
  Number(((Math.max(0, lengthMm) / 1000) * SHELF_SUPPORT_PRICE_PER_METER[finish]).toFixed(2))
);

export const getWardrobeStorageLayerLimit = (heightInput: number) => {
  const heightMm = clampInteger(heightInput, 500, MAX_FURNITURE_PROFILE_MM);
  return Math.max(1, Math.min(
    WARDROBE_MAX_STORAGE_LAYERS,
    Math.floor((heightMm - 40) / WARDROBE_MIN_STORAGE_CLEARANCE_MM) - 1,
  ));
};

export const getWardrobeColumnLimit = (lengthInput: number) => {
  const lengthMm = clampInteger(lengthInput, 400, MAX_FURNITURE_PROFILE_MM);
  return Math.max(1, Math.min(
    WARDROBE_MAX_COLUMNS,
    Math.floor((lengthMm - 20) / WARDROBE_MIN_COLUMN_PITCH_MM),
  ));
};

export const getWardrobeProfileCount = (columnsInput: number, storageLayersInput: number) => {
  const columns = clampInteger(columnsInput, 1, WARDROBE_MAX_COLUMNS);
  const storageLayers = Math.max(1, Math.round(Number(storageLayersInput) || 1));
  const baseProfileCount = 4 * columns + 8;
  const storageProfilesPerLayer = 3 * columns + 1;
  return baseProfileCount + storageLayers * storageProfilesPerLayer;
};

const clampInteger = (value: number, min: number, max: number) => (
  Math.min(max, Math.max(min, Math.round(Number(value) || min)))
);

const createIdFactory = (prefix: string) => {
  let index = 0;
  return (part: string) => `${prefix}-${part}-${++index}`;
};

const createHoles = (
  id: (part: string) => string,
  positions: number[],
  side: ProfileSide,
  options: Pick<DrillHole, 'type' | 'threadSize' | 'fastenerHead' | 'fastenerLengthMm' | 'fastenerDirection'> = {
    type: 'countersunk',
  },
): DrillHole[] => positions.map((positionMm) => ({
  id: id('hole'),
  side,
  positionMm,
  type: options.type,
  threadSize: options.threadSize,
  fastenerHead: options.fastenerHead,
  fastenerLengthMm: options.fastenerLengthMm,
  fastenerDirection: options.fastenerDirection,
  grooveIndex: 0,
  physicalGrooveIndex: 0,
}));

const createProfile = (
  id: (part: string) => string,
  options: {
    variantId: '2020' | '2040';
    length: number;
    position: [number, number, number];
    rotation?: [number, number, number];
    holes?: DrillHole[];
    tappingLeft?: boolean;
    tappingRight?: boolean;
    remark: string;
  },
): ParametricSceneItem => ({
  id: id('profile'),
  kind: 'profile',
  name: options.variantId,
  position: options.position,
  rotation: options.rotation || [0, 0, 0],
  colorId: 'natural',
  quantity: 1,
  variantId: options.variantId,
  length: options.length,
  holes: options.holes || [],
  tappingLeft: !!options.tappingLeft,
  tappingRight: !!options.tappingRight,
  remark: options.remark,
});

export const getCalligraphyCabinetDimensions = (columnsInput: number, layersInput: number) => {
  const maxColumns = Math.floor((CALLIGRAPHY_MAX_LENGTH_MM - CALLIGRAPHY_PROFILE_MM) / (
    CALLIGRAPHY_BASKET_WIDTH_MM + CALLIGRAPHY_PROFILE_MM
  ));
  const maxLayers = Math.floor(
    (CALLIGRAPHY_MAX_HEIGHT_MM
      - CALLIGRAPHY_PROFILE_MM * 2
      - CALLIGRAPHY_LAYER_PITCH_MM / 2) / CALLIGRAPHY_LAYER_PITCH_MM,
  );
  const columns = clampInteger(columnsInput, 1, maxColumns);
  const layers = clampInteger(layersInput, 1, maxLayers);
  return {
    columns,
    layers,
    lengthMm: columns * CALLIGRAPHY_BASKET_WIDTH_MM + (columns + 1) * CALLIGRAPHY_PROFILE_MM,
    heightMm: layers * CALLIGRAPHY_LAYER_PITCH_MM
      + CALLIGRAPHY_LAYER_PITCH_MM / 2
      + CALLIGRAPHY_PROFILE_MM * 2,
    depthMm: CALLIGRAPHY_OUTER_DEPTH_MM,
  };
};

export const getCalligraphyGridForBounds = (lengthInput: number, heightInput: number) => {
  const requestedLengthMm = clampInteger(lengthInput, 340, CALLIGRAPHY_MAX_LENGTH_MM);
  const requestedHeightMm = clampInteger(heightInput, 235, CALLIGRAPHY_MAX_HEIGHT_MM);
  const columns = Math.max(1, Math.floor(
    (requestedLengthMm - CALLIGRAPHY_PROFILE_MM) /
    (CALLIGRAPHY_BASKET_WIDTH_MM + CALLIGRAPHY_PROFILE_MM),
  ));
  const layers = Math.max(1, Math.floor(
    (requestedHeightMm
      - CALLIGRAPHY_PROFILE_MM * 2
      - CALLIGRAPHY_LAYER_PITCH_MM / 2) / CALLIGRAPHY_LAYER_PITCH_MM,
  ));
  return {
    ...getCalligraphyCabinetDimensions(columns, layers),
    requestedLengthMm,
    requestedHeightMm,
  };
};

export const buildCalligraphyCabinetTemplate = (
  columnsInput: number,
  layersInput: number,
): ParametricTemplatePayload => {
  const dimensions = getCalligraphyCabinetDimensions(columnsInput, layersInput);
  const { columns, layers, lengthMm, heightMm, depthMm } = dimensions;
  const id = createIdFactory(`calligraphy-${columns}x${layers}`);
  const items: ParametricSceneItem[] = [];
  const halfLength = lengthMm / 2;
  const halfDepth = depthMm / 2;
  const frontZ = halfDepth - CALLIGRAPHY_PROFILE_MM / 2;
  const backZ = -frontZ;
  const bottomY = CALLIGRAPHY_PROFILE_MM / 2;
  const topY = heightMm - CALLIGRAPHY_PROFILE_MM / 2;
  const verticalLength = heightMm - CALLIGRAPHY_PROFILE_MM * 2;
  const verticalHolePositions = Array.from(
    { length: layers },
    (_, layer) => (layer + 1) * CALLIGRAPHY_LAYER_PITCH_MM,
  );
  const boundaryXs = Array.from(
    { length: columns + 1 },
    (_, boundary) => -halfLength + CALLIGRAPHY_PROFILE_MM / 2
      + boundary * (CALLIGRAPHY_BASKET_WIDTH_MM + CALLIGRAPHY_PROFILE_MM),
  );
  const boundaryHolePositions = boundaryXs.map((x) => x + halfLength);

  // Continuous top and bottom rails span every column at the front and back.
  [frontZ, backZ].forEach((z, faceIndex) => {
    const side: ProfileSide = faceIndex === 0 ? 'B' : 'D';
    items.push(createProfile(id, {
      variantId: '2020',
      length: lengthMm,
      position: [0, bottomY, z],
      holes: [
        ...createHoles(id, boundaryHolePositions, side),
        ...createHoles(id, boundaryHolePositions, 'C', { type: 'through' }),
      ],
      tappingLeft: true,
      tappingRight: true,
      remark: `舒法特柜底部贯通横梁（${faceIndex === 0 ? '前' : '后'}），连接深度梁孔位`,
    }));
    items.push(createProfile(id, {
      variantId: '2020',
      length: lengthMm,
      position: [0, topY, z],
      holes: [
        ...createHoles(id, boundaryHolePositions, side),
        ...createHoles(id, boundaryHolePositions, 'A', { type: 'through' }),
      ],
      tappingLeft: true,
      tappingRight: true,
      remark: `舒法特柜顶部贯通横梁（${faceIndex === 0 ? '前' : '后'}），连接顶部框架深度梁并通孔连接立柱`,
    }));
  });

  boundaryXs.forEach((x, boundary) => {
    [frontZ, backZ].forEach((z, faceIndex) => {
      const side: ProfileSide = faceIndex === 0 ? 'B' : 'D';
      items.push(createProfile(id, {
        variantId: '2020',
        length: verticalLength,
        position: [x, heightMm / 2, z],
        rotation: [0, 0, 90],
        holes: createHoles(id, verticalHolePositions, side),
        tappingLeft: true,
        tappingRight: true,
        remark: `舒法特柜第${boundary + 1}道立柱（${faceIndex === 0 ? '前' : '后'}），沉头孔中心距130mm`,
      }));
    });
  });

  // Bottom and top depth rails are frame-only members on the same planes as
  // the continuous rails. They never receive shelf-support accessories.
  [bottomY, topY].forEach((y, levelIndex) => {
    boundaryXs.forEach((x, boundary) => {
      items.push(createProfile(id, {
        variantId: '2020',
        length: CALLIGRAPHY_BASKET_DEPTH_MM,
        position: [x, y, 0],
        rotation: [0, 90, 0],
        tappingLeft: true,
        tappingRight: true,
        remark: `舒法特柜${levelIndex === 0 ? '底部' : '顶部'}第${boundary + 1}道420mm框架深度梁（不装层板托），两端攻丝`,
      }));
    });
  });

  // Each divider line gets one centered 420 mm rail per layer. Interior rails
  // support baskets on both sides; outer rails only receive the inward support.
  for (let layer = 0; layer < layers; layer += 1) {
    const y = CALLIGRAPHY_PROFILE_MM + (layer + 1) * CALLIGRAPHY_LAYER_PITCH_MM;
    boundaryXs.forEach((x, boundary) => {
      items.push(createProfile(id, {
        variantId: '2020',
        length: CALLIGRAPHY_BASKET_DEPTH_MM,
        position: [x, y, 0],
        rotation: [0, 90, 0],
        tappingLeft: true,
        tappingRight: true,
        remark: `中间第${layer + 1}层第${boundary + 1}道420mm共享承托型材，与立柱孔位对齐并安装层板托，两端攻丝`,
      }));
      const supportSides = [
        ...(boundary > 0 ? [-1] : []),
        ...(boundary < columns ? [1] : []),
      ];
      supportSides.forEach((supportSide) => {
        items.push({
          id: id('support'),
          kind: 'shelf_support',
          name: 'Shelf support',
          position: [x + supportSide * 14, y + 6, 0],
          rotation: [0, 0, 0],
          colorId: 'natural',
          quantity: 1,
          width: 12,
          height: 2,
          thickness: 400,
          finish: 'oxidized',
          accessoryPrice: getShelfSupportUnitPrice(400, 'oxidized'),
          accessoryProfileSize: '2020',
          remark: `第${layer + 1}层第${boundary + 1}道深度梁${supportSide < 0 ? '左' : '右'}侧层板托`,
        });
      });
    });
  }

  const topBoardPieces = lengthMm <= CALLIGRAPHY_TOP_BOARD_MAX_PIECE_MM
    ? [{ startMm: 0, endMm: lengthMm }]
    : (() => {
      // Split only on a vertical divider centerline so every board end remains
      // supported by the existing 2020 frame. Choose the divider nearest the
      // cabinet midpoint while keeping both pieces inside the 2440mm sheet cap.
      const dividerCandidates = boundaryXs.slice(1, -1)
        .map((x) => Math.round(x + halfLength))
        .filter((splitMm) => (
          splitMm <= CALLIGRAPHY_TOP_BOARD_MAX_PIECE_MM
          && lengthMm - splitMm <= CALLIGRAPHY_TOP_BOARD_MAX_PIECE_MM
        ));
      const splitMm = dividerCandidates.sort((first, second) => (
        Math.abs(first - lengthMm / 2) - Math.abs(second - lengthMm / 2)
      ))[0] || Math.ceil(lengthMm / 2);
      return [
        { startMm: 0, endMm: splitMm },
        { startMm: splitMm, endMm: lengthMm },
      ];
    })();
  topBoardPieces.forEach((piece, pieceIndex) => {
    const pieceLength = piece.endMm - piece.startMm;
    items.push({
      id: id('top-board'),
      kind: 'marine_board',
      name: '12mm marine-board top',
      position: [-halfLength + piece.startMm + pieceLength / 2, heightMm + 6, 0],
      rotation: [90, 0, 0],
      colorId: 'wood_natural',
      quantity: 1,
      width: pieceLength,
      height: depthMm,
      thickness: 12,
      remark: topBoardPieces.length === 1
        ? '12mm海洋板整片顶板，覆盖全部型材'
        : `12mm海洋板顶板第${pieceIndex + 1}/${topBoardPieces.length}片，在2020分隔型材中心拼接，单片不超过2440mm`,
    });
  });

  return {
    schemaVersion: 1,
    source: 'calligraphy_cabinet',
    createdAt: new Date().toISOString(),
    summary: {
      columns,
      layers,
      lengthMm,
      heightMm,
      depthMm,
      basketWidthMm: CALLIGRAPHY_BASKET_WIDTH_MM,
      basketDepthMm: CALLIGRAPHY_BASKET_DEPTH_MM,
      basketHeightMm: CALLIGRAPHY_BASKET_HEIGHT_MM,
      holePitchMm: CALLIGRAPHY_LAYER_PITCH_MM,
      topBoardPieces: topBoardPieces.length,
    },
    items,
  };
};

export const buildWardrobeTemplate = (
  lengthInput: number,
  widthInput: number,
  heightInput: number,
  storageLayersInput = 5,
  columnsInput = 1,
): ParametricTemplatePayload => {
  const lengthMm = clampInteger(lengthInput, 400, MAX_FURNITURE_PROFILE_MM);
  const widthMm = clampInteger(widthInput, 300, MAX_FURNITURE_PROFILE_MM);
  const heightMm = clampInteger(heightInput, 500, MAX_FURNITURE_PROFILE_MM);
  const storageLayers = clampInteger(storageLayersInput, 1, getWardrobeStorageLayerLimit(heightMm));
  const columns = clampInteger(columnsInput, 1, getWardrobeColumnLimit(lengthMm));
  const id = createIdFactory(`wardrobe-${columns}col`);
  const items: ParametricSceneItem[] = [];
  const postsByBoundary = new Map<string, ParametricSceneItem>();
  const halfLength = lengthMm / 2;
  const halfWidth = widthMm / 2;
  const bottomY = 10;
  const topY = heightMm - 10;
  const frontPostZ = halfWidth - 20;
  const backPostZ = -frontPostZ;
  const frontRailZ = halfWidth - 10;
  const backRailZ = -frontRailZ;
  const frontShelfRailZ = frontPostZ - WARDROBE_2040_INNER_GROOVE_OFFSET_MM;
  const backShelfRailZ = backPostZ + WARDROBE_2040_INNER_GROOVE_OFFSET_MM;
  const leftX = -halfLength + 10;
  const rightX = halfLength - 10;
  const boundaryXs = Array.from(
    { length: columns + 1 },
    (_, boundaryIndex) => leftX + (boundaryIndex * (rightX - leftX)) / columns,
  );
  const boundaryHolePositions = boundaryXs.map((x) => Number((x + halfLength).toFixed(3)));
  const verticalLength = heightMm - 40;
  const depthRailLength = widthMm - 40;
  const storageDepthRailLength = widthMm - 80;
  const storageLayerYs = Array.from(
    { length: storageLayers },
    (_, layerIndex) => 20 + ((layerIndex + 1) * (heightMm - 40)) / (storageLayers + 1),
  );
  const outerFrameLevels: Array<{
    y: number;
    label: '底部' | '顶部';
    attachmentPrefix: string;
    widthRails: ParametricSceneItem[];
    depthRails: ParametricSceneItem[];
  }> = [];

  // At each level the full-length front/rear rail occupies the outer 20 mm
  // half of the 2040 end face, while the depth rail occupies the inner half.
  // Both therefore press onto separate tapping ports of the vertical 2040.
  [bottomY, topY].forEach((y, levelIndex) => {
    const verticalEntrySide: ProfileSide = levelIndex === 0 ? 'C' : 'A';
    const widthRails = [frontRailZ, backRailZ].map((z, faceIndex) => createProfile(id, {
      variantId: '2020',
      length: lengthMm,
      position: [0, y, z],
      holes: [
        ...createHoles(id, boundaryHolePositions, verticalEntrySide),
        ...createHoles(
          id,
          boundaryHolePositions,
          // B/D is the joint-facing exit side. This short screw enters from
          // the joint and travels outward from the marked face into the
          // perpendicular depth rail's tapped end, opposite to an ordinary
          // face-entry through screw.
          faceIndex === 0 ? 'D' : 'B',
          {
            type: 'through',
            threadSize: 'M6',
            fastenerHead: 'flat_socket',
            fastenerLengthMm: 8,
            fastenerDirection: 'outward',
          },
        ),
      ],
      tappingLeft: true,
      tappingRight: true,
      remark: `衣柜${levelIndex === 0 ? '底部' : '顶部'}${faceIndex === 0 ? '前' : '后'}贯通横梁2020；按${columns + 1}道等分边界连接2040，通孔扁头M6×8拧入各边界深度梁端部攻丝，两端攻丝`,
    }));
    const depthRails = boundaryXs.map((x, boundaryIndex) => createProfile(id, {
      variantId: '2020',
      length: depthRailLength,
      position: [x, y, 0],
      rotation: [0, 90, 0],
      holes: createHoles(id, [10, depthRailLength - 10], verticalEntrySide),
      tappingLeft: true,
      tappingRight: true,
      remark: `衣柜${levelIndex === 0 ? '底部' : '顶部'}第${boundaryIndex + 1}/${columns + 1}道边界深度梁2020；横压前后2040并以沉头螺丝连接，端部攻丝接收相邻2020的扁头M6×8，两端攻丝`,
    }));
    items.push(...widthRails, ...depthRails);
    outerFrameLevels.push({
      y,
      label: levelIndex === 0 ? '底部' : '顶部',
      attachmentPrefix: levelIndex === 0 ? 'WARDROBE:BOTTOM' : 'WARDROBE:TOP',
      widthRails,
      depthRails,
    });
  });

  // [0, 90, 90] turns the 2040 so its 20 mm face is outward in the front
  // view and its 40 mm face runs along the cabinet side/depth direction.
  boundaryXs.forEach((x, boundaryIndex) => [frontPostZ, backPostZ].forEach((z, zIndex) => {
    const post = createProfile(id, {
      variantId: '2040',
      length: verticalLength,
      position: [x, heightMm / 2, z],
      rotation: [0, 90, 90],
      tappingLeft: true,
      tappingRight: true,
      remark: `衣柜第${boundaryIndex + 1}/${columns + 1}道${zIndex === 0 ? '前' : '后'}立柱2040；列边界按正面总长等分，20面朝外、40面朝侧面；中间收纳层使用分列四边框和1号角码，不在立柱开层板连接孔，两端攻丝`,
    });
    items.push(post);
    postsByBoundary.set(`${boundaryIndex}:${zIndex}`, post);
  }));

  const addWardrobeBoardForColumn = ({
    frameY,
    frameLabel,
    attachmentPrefix,
    columnIndex,
    clearDepth,
    frontSupportZ,
    backSupportZ,
    frontRail,
    backRail,
    leftDepthRail,
    rightDepthRail,
  }: {
    frameY: number;
    frameLabel: string;
    attachmentPrefix: string;
    columnIndex: number;
    clearDepth: number;
    frontSupportZ: number;
    backSupportZ: number;
    frontRail: ParametricSceneItem;
    backRail: ParametricSceneItem;
    leftDepthRail: ParametricSceneItem;
    rightDepthRail: ParametricSceneItem;
  }) => {
    const startX = boundaryXs[columnIndex];
    const endX = boundaryXs[columnIndex + 1];
    const clearLength = Number((endX - startX - 20).toFixed(3));
    const boardLength = Number(Math.max(1, clearLength - 2).toFixed(3));
    const boardDepth = Number(Math.max(1, clearDepth - 2).toFixed(3));
    const boardCenterX = Number(((startX + endX) / 2).toFixed(3));
    const boardRemark = `衣柜${frameLabel}第${columnIndex + 1}/${columns}列12mm UV内嵌层板；相对四边2020框内净空长宽各减2mm，四周各留1mm缝隙`;
    const board = {
      id: id('marine-board'),
      kind: 'marine_board' as const,
      name: '12mm UV wardrobe shelf board',
      position: [boardCenterX, frameY + 4, 0] as [number, number, number],
      rotation: [90, 0, 0] as [number, number, number],
      colorId: 'wood_natural',
      quantity: 1,
      width: boardLength,
      height: boardDepth,
      thickness: 12,
      autoGenerated: true,
      lockedPosition: true,
      attachedProfileIds: [
        leftDepthRail.id,
        rightDepthRail.id,
        frontRail.id,
        backRail.id,
      ],
      attachmentKey: `${attachmentPrefix}:${columnIndex + 1}`,
      remark: boardRemark,
    };
    items.push(board);

    const supportY = frameY - 5;
    const supportXOffset = boardLength * 0.3;
    const supportZOffset = boardDepth * 0.3;
    const addBoardSupport = (
      position: [number, number, number],
      rotation: [number, number, number],
      side: string,
      rail: ParametricSceneItem,
    ) => {
      const attachedProfileIds = [board.id, rail.id];
      items.push({
        id: id('shelf-support'),
        kind: 'shelf_support',
        name: '12mm板专用层板托',
        position,
        rotation,
        colorId: 'natural',
        quantity: 1,
        width: 18,
        height: 6,
        thickness: 12,
        finish: 'oxidized',
        shelfSupportType: 'board_12mm',
        accessoryPrice: WARDROBE_12MM_BOARD_SUPPORT_PRICE,
        accessoryProfileSize: '2020',
        autoGenerated: true,
        lockedPosition: true,
        attachedProfileIds,
        attachmentKey: `${board.attachmentKey}:SUPPORT:${side}`,
        remark: `${board.remark}；${side}使用12mm板专用层板托，单价0.7元`,
      });
    };
    [-1, 1].forEach((sign, supportIndex) => {
      addBoardSupport(
        [boardCenterX + sign * supportXOffset, supportY, frontSupportZ],
        [0, 0, 0],
        `前侧${supportIndex + 1}/2`,
        frontRail,
      );
      addBoardSupport(
        [boardCenterX + sign * supportXOffset, supportY, backSupportZ],
        [0, 0, 0],
        `后侧${supportIndex + 1}/2`,
        backRail,
      );
      addBoardSupport(
        [startX + 11, supportY, sign * supportZOffset],
        [0, 90, 0],
        `左侧${supportIndex + 1}/2`,
        leftDepthRail,
      );
      addBoardSupport(
        [endX - 11, supportY, sign * supportZOffset],
        [0, 90, 0],
        `右侧${supportIndex + 1}/2`,
        rightDepthRail,
      );
    });
  };

  outerFrameLevels.forEach((level) => {
    for (let columnIndex = 0; columnIndex < columns; columnIndex += 1) {
      addWardrobeBoardForColumn({
        frameY: level.y,
        frameLabel: level.label,
        attachmentPrefix: level.attachmentPrefix,
        columnIndex,
        clearDepth: depthRailLength,
        frontSupportZ: frontRailZ - 1,
        backSupportZ: backRailZ + 1,
        frontRail: level.widthRails[0],
        backRail: level.widthRails[1],
        leftDepthRail: level.depthRails[columnIndex],
        rightDepthRail: level.depthRails[columnIndex + 1],
      });
    }
  });

  // Every column at every requested storage level is a complete four-sided
  // 2020 rectangle. Front/rear rails are split at divider posts so they cannot
  // pass through an intermediate 2040 solid; adjacent columns share their
  // boundary depth rail. No shelf-frame member is tapped and no matching
  // countersunk hole is added to the posts.
  storageLayerYs.forEach((y, layerIndex) => {
    const layerY = Math.round(y);
    const depthRails = boundaryXs.map((x, boundaryIndex) => createProfile(id, {
      variantId: '2020',
      length: storageDepthRailLength,
      position: [x, layerY, 0],
      rotation: [0, 90, 0],
      remark: `衣柜第${layerIndex + 1}个收纳层第${boundaryIndex + 1}/${columns + 1}道共享边界深度横杆2020；相邻列共用并与前后分段横杆组成闭合四边框，使用1号角码，不攻丝`,
    }));
    const widthRailsByColumn = boundaryXs.slice(0, -1).map((startX, columnIndex) => {
      const endX = boundaryXs[columnIndex + 1];
      const railLength = Number((endX - startX - 20).toFixed(3));
      const railCenterX = Number(((startX + endX) / 2).toFixed(3));
      return [frontShelfRailZ, backShelfRailZ].map((z, faceIndex) => createProfile(id, {
        variantId: '2020',
        length: railLength,
        position: [railCenterX, layerY, z],
        remark: `衣柜第${layerIndex + 1}个收纳层第${columnIndex + 1}/${columns}列${faceIndex === 0 ? '前' : '后'}侧${railLength}mm分段横杆2020；默认落在2040朝柜内的槽位，端面贴齐相邻列边界立柱并以1号角码连接，不攻丝`,
      }));
    });
    const widthRails = widthRailsByColumn.flat();
    items.push(...depthRails, ...widthRails);

    widthRailsByColumn.forEach((columnRails, columnIndex) => {
      addWardrobeBoardForColumn({
        frameY: layerY,
        frameLabel: `第${layerIndex + 1}个收纳层`,
        attachmentPrefix: `WARDROBE:SHELF:${layerIndex + 1}`,
        columnIndex,
        clearDepth: storageDepthRailLength,
        frontSupportZ: frontShelfRailZ - 1,
        backSupportZ: backShelfRailZ + 1,
        frontRail: columnRails[0],
        backRail: columnRails[1],
        leftDepthRail: depthRails[columnIndex],
        rightDepthRail: depthRails[columnIndex + 1],
      });
    });

    const addLayerBracket = (
      rail: ParametricSceneItem,
      post: ParametricSceneItem,
      location: string,
    ) => {
      const attachedProfileIds = [rail.id, post.id];
      items.push({
        id: id('connector'),
        kind: 'connector',
        name: 'No.1 corner bracket',
        // The designer resolves the exact contact point and orientation from
        // these two attached profiles when it consumes the template.
        position: [0, layerY, 0],
        rotation: [0, 0, 0],
        colorId: 'natural',
        quantity: 1,
        width: 20,
        height: 20,
        thickness: 3.2,
        accessoryPrice: 1,
        accessoryProfileSize: '2020',
        autoGenerated: true,
        lockedPosition: true,
        attachedProfileIds,
        attachmentKey: attachedProfileIds.slice().sort().join(':JOINT:'),
        remark: `衣柜第${layerIndex + 1}个收纳层${location}横杆—立柱1号角码；两条90°贴边分别紧贴横杆和立柱`,
      });
    };
    depthRails.forEach((depthRail, boundaryIndex) => [0, 1].forEach((zIndex) => {
      const post = postsByBoundary.get(`${boundaryIndex}:${zIndex}`);
      if (post) addLayerBracket(
        depthRail,
        post,
        `第${boundaryIndex + 1}道边界${zIndex === 0 ? '前' : '后'}侧`,
      );
    }));
    widthRailsByColumn.forEach((columnRails, columnIndex) => {
      columnRails.forEach((widthRail, zIndex) => [columnIndex, columnIndex + 1].forEach((boundaryIndex) => {
        const post = postsByBoundary.get(`${boundaryIndex}:${zIndex}`);
        if (post) addLayerBracket(
          widthRail,
          post,
          `第${columnIndex + 1}列${zIndex === 0 ? '前' : '后'}侧${boundaryIndex === columnIndex ? '左' : '右'}端`,
        );
      }));
    });
  });

  const baseProfileCount = 4 * columns + 8;
  const storageProfilesPerLayer = 3 * columns + 1;
  const storageConnectorsPerLayer = 6 * columns + 2;
  const shelfBoardCount = (storageLayers + 2) * columns;
  const boardShelfSupportCount = shelfBoardCount * 8;

  return {
    schemaVersion: 1,
    source: 'wardrobe',
    createdAt: new Date().toISOString(),
    summary: {
      lengthMm,
      widthMm,
      heightMm,
      columns,
      columnWidthMm: Number((lengthMm / columns).toFixed(2)),
      storageLayers,
      baseProfileCount,
      storageProfilesPerLayer,
      storageConnectorsPerLayer,
      profileCount: baseProfileCount + storageLayers * storageProfilesPerLayer,
      connectorCount: storageLayers * storageConnectorsPerLayer,
      shelfBoardCount,
      boardShelfSupportCount,
      horizontalProfile: '2020',
      verticalProfile: '2040',
    },
    items,
  };
};
