import { strFromU8, unzipSync } from 'fflate';

type WorkbookCell = string | number | null | undefined;

export interface ProductionWorkbookData {
  parts: Array<{
    line: number;
    id: string;
    type: string;
    model: string;
    accessoryProfileSize?: string;
    accessoryThreadSize?: string;
    hasBrake?: boolean;
    attachedEnd?: 'left' | 'right';
    autoAddedTapping?: boolean;
    doorMaterial?: string;
    doorOverlay?: string;
    openingSide?: string;
    lengthMm?: number;
    widthMm?: number;
    heightMm?: number;
    thicknessMm?: number;
    finish?: string;
    colorId?: string;
    color: string;
    pegHolePattern?: string;
    quantity: number;
    positionMm: number[];
    rotationDeg: number[];
    leftTappingPorts: number;
    rightTappingPorts: number;
    screwHead?: string;
    linkedProfileId?: string;
    linkedHoleId?: string;
    autoGenerated?: boolean;
    lockedPosition?: boolean;
    attachedProfileIds?: string[];
    attachmentKey?: string;
    remark: string;
  }>;
  holes: Array<{
    partLine: number;
    partId?: string;
    model: string;
    holeLine: number;
    holeId?: string;
    jointKey?: string;
    entryFace: string;
    entryGroove: string;
    exitFace: string;
    exitGroove: string;
    physicalGrooveId: string;
    leftDistanceMm: number;
    rightDistanceMm: number;
    holeType: string;
    threadSize: string;
    fastenerHead?: string;
    fastenerLengthMm?: number;
    fastenerDirection?: 'inward' | 'outward';
    verification: string;
  }>;
}

type SheetDefinition = {
  name: string;
  title: string;
  headers: string[];
  rows: WorkbookCell[][];
  widths: number[];
};

const encoder = new TextEncoder();

const xmlEscape = (value: unknown) => String(value ?? '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&apos;');

const columnName = (index: number) => {
  let current = index + 1;
  let result = '';
  while (current > 0) {
    const remainder = (current - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    current = Math.floor((current - 1) / 26);
  }
  return result;
};

const cellXml = (value: WorkbookCell, rowIndex: number, columnIndex: number, style: number) => {
  const reference = `${columnName(columnIndex)}${rowIndex}`;
  if (typeof value === 'number' && Number.isFinite(value)) {
    return `<c r="${reference}" s="${style}"><v>${value}</v></c>`;
  }
  const escaped = xmlEscape(value);
  const preserve = /^\s|\s$|\n/.test(String(value ?? '')) ? ' xml:space="preserve"' : '';
  return `<c r="${reference}" s="${style}" t="inlineStr"><is><t${preserve}>${escaped}</t></is></c>`;
};

const worksheetXml = (sheet: SheetDefinition) => {
  const columnCount = sheet.headers.length;
  const titleCell = cellXml(sheet.title, 1, 0, 1);
  const headerCells = sheet.headers.map((value, index) => cellXml(value, 2, index, 2)).join('');
  const rows = sheet.rows.map((row, rowIndex) => {
    const cells = row.map((value, columnIndex) => {
      const isNumber = typeof value === 'number' && Number.isFinite(value);
      const isLongText = columnIndex === row.length - 1 || String(value ?? '').length > 28;
      return cellXml(value, rowIndex + 3, columnIndex, isLongText ? 5 : isNumber ? 4 : 3);
    }).join('');
    return `<row r="${rowIndex + 3}" ht="${row.some((value) => String(value ?? '').length > 42) ? 32 : 22}" customHeight="1">${cells}</row>`;
  }).join('');
  const columns = sheet.widths.map((width, index) => (
    `<col min="${index + 1}" max="${index + 1}" width="${width}" customWidth="1"/>`
  )).join('');

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="2" topLeftCell="A3" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>
  <sheetFormatPr defaultRowHeight="18"/>
  <cols>${columns}</cols>
  <sheetData>
    <row r="1" ht="30" customHeight="1">${titleCell}</row>
    <row r="2" ht="28" customHeight="1">${headerCells}</row>
    ${rows}
  </sheetData>
  <mergeCells count="1"><mergeCell ref="A1:${columnName(columnCount - 1)}1"/></mergeCells>
  <autoFilter ref="A2:${columnName(columnCount - 1)}${Math.max(2, sheet.rows.length + 2)}"/>
  <pageMargins left="0.3" right="0.3" top="0.5" bottom="0.5" header="0.2" footer="0.2"/>
</worksheet>`;
};

const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="3">
    <font><sz val="10"/><name val="Arial"/></font>
    <font><b/><sz val="16"/><color rgb="FFFFFFFF"/><name val="Arial"/></font>
    <font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Arial"/></font>
  </fonts>
  <fills count="4">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF0F172A"/><bgColor indexed="64"/></patternFill></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF2563EB"/><bgColor indexed="64"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border><left style="thin"><color rgb="FFE2E8F0"/></left><right style="thin"><color rgb="FFE2E8F0"/></right><top style="thin"><color rgb="FFE2E8F0"/></top><bottom style="thin"><color rgb="FFE2E8F0"/></bottom><diagonal/></border>
  </borders>
  <cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
  <cellXfs count="6">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center"/></xf>
    <xf numFmtId="0" fontId="2" fillId="3" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment vertical="center"/></xf>
    <xf numFmtId="1" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1" applyAlignment="1"><alignment horizontal="right" vertical="center"/></xf>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf>
  </cellXfs>
  <cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>
</styleSheet>`;

const crcTable = (() => {
  const table = new Uint32Array(256);
  for (let index = 0; index < 256; index += 1) {
    let value = index;
    for (let bit = 0; bit < 8; bit += 1) {
      value = (value & 1) ? (0xedb88320 ^ (value >>> 1)) : (value >>> 1);
    }
    table[index] = value >>> 0;
  }
  return table;
})();

const crc32 = (bytes: Uint8Array) => {
  let crc = 0xffffffff;
  bytes.forEach((byte) => {
    crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  });
  return (crc ^ 0xffffffff) >>> 0;
};

const concatBytes = (chunks: Uint8Array[]) => {
  const output = new Uint8Array(chunks.reduce((sum, chunk) => sum + chunk.length, 0));
  let offset = 0;
  chunks.forEach((chunk) => {
    output.set(chunk, offset);
    offset += chunk.length;
  });
  return output;
};

const zipStore = (entries: Array<{ name: string; content: string }>) => {
  const localChunks: Uint8Array[] = [];
  const centralChunks: Uint8Array[] = [];
  let localOffset = 0;
  const now = new Date();
  const dosTime = ((now.getHours() & 0x1f) << 11) | ((now.getMinutes() & 0x3f) << 5) | ((Math.floor(now.getSeconds() / 2)) & 0x1f);
  const dosDate = (((now.getFullYear() - 1980) & 0x7f) << 9) | (((now.getMonth() + 1) & 0x0f) << 5) | (now.getDate() & 0x1f);

  entries.forEach((entry) => {
    const name = encoder.encode(entry.name);
    const content = encoder.encode(entry.content);
    const checksum = crc32(content);
    const local = new Uint8Array(30 + name.length);
    const localView = new DataView(local.buffer);
    localView.setUint32(0, 0x04034b50, true);
    localView.setUint16(4, 20, true);
    localView.setUint16(6, 0x0800, true);
    localView.setUint16(8, 0, true);
    localView.setUint16(10, dosTime, true);
    localView.setUint16(12, dosDate, true);
    localView.setUint32(14, checksum, true);
    localView.setUint32(18, content.length, true);
    localView.setUint32(22, content.length, true);
    localView.setUint16(26, name.length, true);
    local.set(name, 30);
    localChunks.push(local, content);

    const central = new Uint8Array(46 + name.length);
    const centralView = new DataView(central.buffer);
    centralView.setUint32(0, 0x02014b50, true);
    centralView.setUint16(4, 20, true);
    centralView.setUint16(6, 20, true);
    centralView.setUint16(8, 0x0800, true);
    centralView.setUint16(10, 0, true);
    centralView.setUint16(12, dosTime, true);
    centralView.setUint16(14, dosDate, true);
    centralView.setUint32(16, checksum, true);
    centralView.setUint32(20, content.length, true);
    centralView.setUint32(24, content.length, true);
    centralView.setUint16(28, name.length, true);
    centralView.setUint32(42, localOffset, true);
    central.set(name, 46);
    centralChunks.push(central);
    localOffset += local.length + content.length;
  });

  const centralDirectory = concatBytes(centralChunks);
  const end = new Uint8Array(22);
  const endView = new DataView(end.buffer);
  endView.setUint32(0, 0x06054b50, true);
  endView.setUint16(8, entries.length, true);
  endView.setUint16(10, entries.length, true);
  endView.setUint32(12, centralDirectory.length, true);
  endView.setUint32(16, localOffset, true);
  return concatBytes([...localChunks, centralDirectory, end]);
};

export const buildProductionXlsx = (production: ProductionWorkbookData) => {
  const guideRows: WorkbookCell[][] = [
    ['核心规则', 'physicalGrooveIndex（P1/P2…）是3D、客户图和工厂图的唯一物理槽位基准。'],
    ['2040示例', 'B面第一槽 = 物理P1 = D面第二槽；B面第二槽 = 物理P2 = D面第一槽。'],
    ['生产核对', '加工前同时核对入口面/槽、出口面/槽、物理槽ID及距左右端尺寸。'],
  ];
  const partRows = production.parts.map((part) => [
    part.line, part.id, part.type, part.model, part.accessoryProfileSize ?? '', part.lengthMm ?? '', part.widthMm ?? '', part.heightMm ?? '',
    part.thicknessMm ?? '', part.finish ?? '', part.color, part.colorId ?? '', part.quantity, part.pegHolePattern ?? '', part.positionMm.join(', '), part.rotationDeg.join(', '),
    part.leftTappingPorts, part.rightTappingPorts, part.screwHead ?? '', part.linkedProfileId ?? '', part.linkedHoleId ?? '',
    part.autoGenerated ? '是' : '', part.lockedPosition ? '是' : '', (part.attachedProfileIds || []).join(', '), part.attachmentKey ?? '',
    part.accessoryThreadSize ?? '', part.hasBrake === undefined ? '' : part.hasBrake ? '是' : '否',
    part.attachedEnd === 'left' ? '左端' : part.attachedEnd === 'right' ? '右端' : '',
    part.autoAddedTapping === undefined ? '' : part.autoAddedTapping ? '是' : '否',
    part.doorMaterial === 'marine' ? '海洋板门' : part.doorMaterial === 'pegboard' ? '铝洞洞板门' : part.doorMaterial === 'aluminum' ? '铝柜门' : '',
    part.doorOverlay === 'half' ? '半盖' : part.doorOverlay === 'inset' ? '大弯（不盖型材）' : part.doorOverlay === 'full' ? '全盖' : '',
    part.openingSide === 'right' ? '右开' : part.openingSide === 'left' ? '左开' : '', part.remark,
  ]);
  const holeRows = production.holes.map((hole) => [
    hole.partLine, hole.partId ?? '', hole.model, hole.holeLine, hole.holeId ?? '', hole.jointKey ?? '', hole.entryFace, hole.entryGroove, hole.exitFace, hole.exitGroove,
    hole.physicalGrooveId, hole.leftDistanceMm, hole.rightDistanceMm, hole.holeType, hole.threadSize,
    hole.fastenerHead ?? '', hole.fastenerLengthMm ?? '', hole.fastenerDirection === 'outward' ? '向外/进入相邻型材' : '向内/穿入本型材', hole.verification,
  ]);
  const sheets: SheetDefinition[] = [
    {
      name: '核对说明',
      title: '萌开了 3D DIY 生产核对说明',
      headers: ['项目', '说明'],
      rows: guideRows,
      widths: [18, 88],
    },
    {
      name: '零件明细',
      title: '萌开了 3D DIY 零件明细',
      headers: ['序号', '零件ID', '类型', '型号', '适配型材规格', '长度mm', '宽度mm', '高度mm', '厚度mm', '截面/表面档位', '颜色', '颜色ID', '数量', '洞洞板孔型', '位置XYZ(mm)', '旋转XYZ(°)', '左端攻丝孔数', '右端攻丝孔数', '螺丝头型', '关联型材ID', '关联孔ID', '自动生成', '位置锁定', '连接型材ID', '连接关系ID', '配件螺纹规格', '带刹车', '端盖端面', '端盖自动攻丝', '柜门材料', '柜门覆盖方式', '柜门开向', '备注'],
      rows: partRows,
      widths: [8, 25, 14, 14, 16, 12, 12, 12, 12, 18, 15, 14, 9, 14, 20, 20, 15, 15, 14, 25, 25, 12, 12, 38, 38, 16, 12, 12, 16, 14, 16, 12, 38],
    },
    {
      name: '打孔明细',
      title: '萌开了 3D DIY 打孔明细',
      headers: ['零件序号', '零件ID', '型号', '孔序号', '孔ID', '连接关系ID', '入口面', '入口二维槽位', '出口面', '出口二维槽位', '物理槽ID', '距左端mm', '距右端mm', '孔类型', '螺纹', '指定螺丝头型', '指定螺丝长度mm', '螺丝进入方向', '客户/工厂核对'],
      rows: holeRows,
      widths: [11, 25, 14, 10, 25, 28, 10, 15, 10, 15, 12, 13, 13, 14, 10, 16, 17, 22, 42],
    },
  ];

  const workbookSheets = sheets.map((sheet, index) => (
    `<sheet name="${xmlEscape(sheet.name)}" sheetId="${index + 1}" r:id="rId${index + 1}"/>`
  )).join('');
  const workbookRelationships = sheets.map((_, index) => (
    `<Relationship Id="rId${index + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${index + 1}.xml"/>`
  )).join('');
  const contentOverrides = sheets.map((_, index) => (
    `<Override PartName="/xl/worksheets/sheet${index + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`
  )).join('');

  const entries = [
    {
      name: '[Content_Types].xml',
      content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
  ${contentOverrides}
</Types>`,
    },
    {
      name: '_rels/.rels',
      content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`,
    },
    {
      name: 'xl/workbook.xml',
      content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <bookViews><workbookView xWindow="0" yWindow="0" windowWidth="24000" windowHeight="12000"/></bookViews>
  <sheets>${workbookSheets}</sheets>
</workbook>`,
    },
    {
      name: 'xl/_rels/workbook.xml.rels',
      content: `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  ${workbookRelationships}
  <Relationship Id="rId${sheets.length + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>`,
    },
    { name: 'xl/styles.xml', content: stylesXml },
    ...sheets.map((sheet, index) => ({
      name: `xl/worksheets/sheet${index + 1}.xml`,
      content: worksheetXml(sheet),
    })),
  ];
  return zipStore(entries);
};

const RELATIONSHIP_NAMESPACE = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships';

const xmlDocument = (content: Uint8Array) => new DOMParser().parseFromString(strFromU8(content), 'application/xml');

const columnIndexFromReference = (reference: string) => {
  const letters = reference.match(/^[A-Z]+/)?.[0] || 'A';
  return letters.split('').reduce((value, letter) => value * 26 + letter.charCodeAt(0) - 64, 0) - 1;
};

const workbookSheetPath = (
  files: Record<string, Uint8Array>,
  sheetName: string,
  fallbackPath: string,
) => {
  const workbook = files['xl/workbook.xml'];
  const relationships = files['xl/_rels/workbook.xml.rels'];
  if (!workbook || !relationships) return fallbackPath;
  const workbookDoc = xmlDocument(workbook);
  const relationshipDoc = xmlDocument(relationships);
  const sheet = Array.from(workbookDoc.getElementsByTagName('sheet'))
    .find((entry) => entry.getAttribute('name') === sheetName);
  const relationId = sheet?.getAttribute('r:id') || sheet?.getAttributeNS(RELATIONSHIP_NAMESPACE, 'id');
  if (!relationId) return fallbackPath;
  const relationship = Array.from(relationshipDoc.getElementsByTagName('Relationship'))
    .find((entry) => entry.getAttribute('Id') === relationId);
  const target = relationship?.getAttribute('Target');
  if (!target) return fallbackPath;
  if (target.startsWith('/')) return target.slice(1);
  return target.startsWith('xl/') ? target : `xl/${target.replace(/^\.\//, '')}`;
};

const sharedStringValues = (files: Record<string, Uint8Array>) => {
  const sharedStrings = files['xl/sharedStrings.xml'];
  if (!sharedStrings) return [];
  const document = xmlDocument(sharedStrings);
  return Array.from(document.getElementsByTagName('si')).map((item) => (
    Array.from(item.getElementsByTagName('t')).map((text) => text.textContent || '').join('')
  ));
};

const worksheetRecords = (
  files: Record<string, Uint8Array>,
  path: string,
  sharedStrings: string[],
) => {
  const worksheet = files[path];
  if (!worksheet) return [];
  const document = xmlDocument(worksheet);
  const rows = Array.from(document.getElementsByTagName('row')).map((row) => {
    const values: string[] = [];
    Array.from(row.getElementsByTagName('c')).forEach((cell) => {
      const index = columnIndexFromReference(cell.getAttribute('r') || 'A1');
      const type = cell.getAttribute('t');
      const inlineText = Array.from(cell.getElementsByTagName('t')).map((text) => text.textContent || '').join('');
      const rawValue = cell.getElementsByTagName('v')[0]?.textContent || '';
      values[index] = type === 's' ? sharedStrings[Number(rawValue)] || '' : inlineText || rawValue;
    });
    return values;
  });
  const headers = rows[1] || [];
  return rows.slice(2).filter((row) => row.some((value) => value !== '')).map((row) => (
    headers.reduce<Record<string, string>>((record, header, index) => {
      if (header) record[header] = row[index] || '';
      return record;
    }, {})
  ));
};

const optionalNumber = (value: string) => {
  if (value === '') return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
};

const vectorValues = (value: string) => {
  const values = String(value || '').split(/[,，\s]+/).filter(Boolean).map(Number).filter(Number.isFinite);
  return values.length === 3 ? values : [0, 0, 0];
};

export const parseProductionXlsx = (content: ArrayBuffer): ProductionWorkbookData => {
  const files = unzipSync(new Uint8Array(content));
  const sharedStrings = sharedStringValues(files);
  const partRecords = worksheetRecords(
    files,
    workbookSheetPath(files, '零件明细', 'xl/worksheets/sheet2.xml'),
    sharedStrings,
  );
  const holeRecords = worksheetRecords(
    files,
    workbookSheetPath(files, '打孔明细', 'xl/worksheets/sheet3.xml'),
    sharedStrings,
  );
  if (!partRecords.length) throw new Error('No production parts found in workbook');
  return {
    parts: partRecords.map((record, index) => ({
      line: optionalNumber(record['序号']) || index + 1,
      id: record['零件ID'] || `excel_part_${index + 1}`,
      type: record['类型'] || '',
      model: record['型号'] || '',
      accessoryProfileSize: record['适配型材规格'] || undefined,
      accessoryThreadSize: record['配件螺纹规格'] || undefined,
      hasBrake: record['带刹车'] === '是',
      attachedEnd: record['端盖端面'] === '左端' ? 'left' : record['端盖端面'] === '右端' ? 'right' : undefined,
      autoAddedTapping: record['端盖自动攻丝'] ? record['端盖自动攻丝'] === '是' : undefined,
      doorMaterial: record['柜门材料'] === '海洋板门' ? 'marine' : record['柜门材料'] === '铝洞洞板门' ? 'pegboard' : record['柜门材料'] === '铝柜门' ? 'aluminum' : record['柜门材料'] || undefined,
      doorOverlay: record['柜门覆盖方式'] === '半盖' ? 'half' : (record['柜门覆盖方式'] || '').includes('大弯') ? 'inset' : record['柜门覆盖方式'] === '全盖' ? 'full' : record['柜门覆盖方式'] || undefined,
      openingSide: record['柜门开向'] === '右开' ? 'right' : record['柜门开向'] === '左开' ? 'left' : record['柜门开向'] || undefined,
      lengthMm: optionalNumber(record['长度mm']),
      widthMm: optionalNumber(record['宽度mm']),
      heightMm: optionalNumber(record['高度mm']),
      thicknessMm: optionalNumber(record['厚度mm']),
      finish: record['截面/表面档位'] || undefined,
      color: record['颜色'] || '',
      colorId: record['颜色ID'] || undefined,
      quantity: optionalNumber(record['数量']) || 1,
      pegHolePattern: record['洞洞板孔型'] || undefined,
      positionMm: vectorValues(record['位置XYZ(mm)']),
      rotationDeg: vectorValues(record['旋转XYZ(°)']),
      leftTappingPorts: optionalNumber(record['左端攻丝孔数']) || 0,
      rightTappingPorts: optionalNumber(record['右端攻丝孔数']) || 0,
      screwHead: record['螺丝头型'] || undefined,
      linkedProfileId: record['关联型材ID'] || undefined,
      linkedHoleId: record['关联孔ID'] || undefined,
      autoGenerated: record['自动生成'] === '是',
      lockedPosition: record['位置锁定'] === '是',
      attachedProfileIds: record['连接型材ID'] ? record['连接型材ID'].split(',').map((value) => value.trim()).filter(Boolean) : undefined,
      attachmentKey: record['连接关系ID'] || undefined,
      remark: record['备注'] || '',
    })),
    holes: holeRecords.map((record, index) => ({
      partLine: optionalNumber(record['零件序号']) || 0,
      partId: record['零件ID'] || undefined,
      model: record['型号'] || '',
      holeLine: optionalNumber(record['孔序号']) || index + 1,
      holeId: record['孔ID'] || undefined,
      jointKey: record['连接关系ID'] || undefined,
      entryFace: record['入口面'] || 'A',
      entryGroove: record['入口二维槽位'] || '-',
      exitFace: record['出口面'] || 'C',
      exitGroove: record['出口二维槽位'] || '-',
      physicalGrooveId: record['物理槽ID'] || 'P1',
      leftDistanceMm: optionalNumber(record['距左端mm']) || 0,
      rightDistanceMm: optionalNumber(record['距右端mm']) || 0,
      holeType: record['孔类型'] || 'through',
      threadSize: record['螺纹'] || '',
      fastenerHead: record['指定螺丝头型'] || undefined,
      fastenerLengthMm: optionalNumber(record['指定螺丝长度mm']),
      fastenerDirection: record['螺丝进入方向'] === '向外/进入相邻型材' ? 'outward' : undefined,
      verification: record['客户/工厂核对'] || '',
    })),
  };
};
