import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import {
  buildDesignDocument,
  buildProductionData,
  inspectDesignerManufacturingPrecheck,
  normalizeDesignItems,
  synchronizeDesignerSceneItems,
} from '../components/DIYDesigner';
import { STOOL_ACCESSORY_CATALOG } from '../data/stoolAccessoryCatalog';
import { createDesignSourceInfo } from '../utils/designSource';
import { inspectDesignerImportItems } from '../utils/designerImportPreflight';
import { rekeyImportedDesignItems } from '../utils/designerImportRemap';
import { buildMaterialList } from '../utils/materialList';
import { buildStoolTemplateFromAsset, buildStoolSourceTemplateFromAsset, STOOL_BASELINE, type StoolSourceAsset } from '../utils/parametricStool';
import { getStoolAccessoryGeometrySignature, loadStoolAccessoryItem, resolveStoolAccessoryReference } from '../utils/stoolAccessoryAssets';

// Asset hashes, GLB triangulation and thumbnail contents are checked separately
// by verify-stool-accessory-assets. This exercises the designer's actual data path.
type Scene = ReturnType<typeof synchronizeDesignerSceneItems>;
const provenance = createDesignSourceInfo('manual_designer');
const moneyKeys = /^(?:accessoryPrice|price|unitPrice|totalPrice|amount|cost|subtotal|totalAmount|currency)$/i;
const assertPriceFree = (value: unknown, location: string): void => {
  if (!value || typeof value !== 'object') return;
  for (const [key, child] of Object.entries(value)) {
    assert.equal(moneyKeys.test(key), false, `${location}.${key} must not contain commerce fields`);
    if (child && typeof child === 'object') assertPriceFree(child, `${location}.${key}`);
  }
};
const importScene = (items: Parameters<typeof normalizeDesignItems>[0]) => {
  const check = inspectDesignerImportItems(items);
  assert.equal(check.valid, true, JSON.stringify(check.issues));
  return synchronizeDesignerSceneItems(normalizeDesignItems(items));
};
const catalogItems = (items: Scene) => items.filter(item => item.kind === 'imported_component' && item.partCatalogRef);
const assertCatalogIdentity = (items: Scene) => {
  for (const item of items) {
    assert.equal(item.kind, 'imported_component');
    assert.ok(item.sourceMesh);
    assert.deepEqual(item.partCatalogRef, resolveStoolAccessoryReference(item.sourceMesh));
    assert.ok(item.partCatalogRef, 'Exact accessory source geometry must retain its independent identity');
    assert.equal(item.catalogItemId, undefined, 'Independent design identity must not be promoted to a procurement SKU');
    assert.equal(item.fastenerCatalogId, undefined);
    assert.equal(item.autoGenerated, false);
    assert.equal(item.quantity, 1);
  }
};
const assertDraftList = (items: Scene, expectedAccessoryCount: number) => {
  const accessoryItems = catalogItems(items);
  assert.equal(accessoryItems.length, expectedAccessoryCount);
  assertCatalogIdentity(accessoryItems);
  const data = buildProductionData(items, 'cn');
  const list = buildMaterialList(data);
  const rows = list.sections.flatMap(section => section.rows);
  let quantity = 0;
  for (const entry of STOOL_ACCESSORY_CATALOG) {
    const expected = accessoryItems.filter(item => item.partCatalogRef?.catalogItemId === entry.catalogItemId);
    const actual = rows.filter(row => row.catalogItemId === entry.catalogItemId);
    assert.equal(actual.reduce((sum, row) => sum + row.quantity, 0), expected.length);
    assert.ok(actual.every(row => row.state === 'design_only' && row.bomOnly === false));
    assert.deepEqual(actual.flatMap(row => row.partIds).sort(), expected.map(item => item.id).sort());
    expected.forEach(item => {
      const part = data.parts.find(candidate => candidate.id === item.id)!;
      assert.equal(part.type, 'imported_component');
      assert.deepEqual(part.partCatalogRef, item.partCatalogRef);
      assert.equal(part.sourceGeometry?.reviewStatus, 'source_geometry_only');
      assert.ok(part.designDraftMarkers.includes('sourceMesh'));
    });
    quantity += expected.length;
  }
  assert.equal(quantity, expectedAccessoryCount);
  assert.ok(list.hasReviewRequired);
  assertPriceFree(data, 'productionProjection');
  assertPriceFree(list, 'materialList');
  return list;
};
const saveDraft = (items: Scene) => {
  const precheck = inspectDesignerManufacturingPrecheck(items);
  // Source accessories are all catalogue-identified, so nothing is *computed*
  // to be wrong: the design is releasable once its outstanding statements are
  // accepted, and it still ships no production projection before that.
  assert.equal(precheck.blocking.length, 0);
  assert.equal(precheck.valid, true);
  assert.ok(precheck.advisories.length > 0);
  assert.ok(precheck.scopes.includes('source_mesh_draft'));
  const document = buildDesignDocument(items, 'cn', provenance);
  assert.ok('productionRelease' in document);
  assert.equal(document.productionRelease.status, 'requires_acknowledgement');
  assert.equal('production' in document, false, 'Editable files must not present draft accessories as manufacturing-ready');
  assertPriceFree(document, 'editableDocument');
  const accepted = buildDesignDocument(items, 'cn', provenance, null, {
    manufacturingAcknowledgement: {
      advisories: document.productionRelease.advisories,
      acknowledgedAt: '2026-10-03T00:00:00.000Z',
    },
  });
  assert.equal(accepted.productionRelease.status, 'acknowledged');
  assert.ok('production' in accepted);
  assertPriceFree(accepted, 'acknowledgedDocument');
  return document;
};

async function main() {
// Follow the same async loader and insertion data path as the palette button.
const originalFetch = globalThis.fetch;
globalThis.fetch = async input => {
  const url = new URL(String(input), 'http://localhost');
  return new Response(readFileSync(path.resolve('public', `.${url.pathname}`)), { status: 200 });
};
const loaded = await (async () => {
  try {
    return await Promise.all(STOOL_ACCESSORY_CATALOG.map((entry, index) => loadStoolAccessoryItem(entry.id, {
      id: `stool-accessory-contract-${entry.id}`,
      position: [index * 180, 120, -90], rotation: [10 * index, 15 * index, 20 * index],
    })));
  } finally { globalThis.fetch = originalFetch; }
})();
const inserted = importScene(loaded);
assert.equal(inserted.length, STOOL_ACCESSORY_CATALOG.length, 'Adding source accessories must not infer generic feet, wheels or screws');
inserted.forEach((item, index) => {
  assert.equal(item.sourceMesh, loaded[index].sourceMesh, 'Insertion preserves the immutable original mesh');
  assert.deepEqual(item.position, loaded[index].position);
  assert.deepEqual(item.rotation, loaded[index].rotation);
  saveDraft([item]);
});
assertDraftList(inserted, 3);
const saved = saveDraft(inserted);
const reopened = importScene(JSON.parse(JSON.stringify(saved)).items);
assertDraftList(reopened, 3);
reopened.forEach((item, index) => {
  assert.deepEqual(item.partCatalogRef, inserted[index].partCatalogRef);
  assert.deepEqual(item.sourceMesh, inserted[index].sourceMesh, 'JSON roundtrip retains vertices, normals, materials, textures and provenance');
  assert.deepEqual(item.position, inserted[index].position);
  assert.deepEqual(item.rotation, inserted[index].rotation);
});
saveDraft(reopened);

// The product-page download must work as a standalone reopen, not just through
// the palette loader. Geometry remains fixed regardless of its scene transform.
for (const entry of STOOL_ACCESSORY_CATALOG) {
  const download = JSON.parse(readFileSync(path.resolve('public', `.${entry.sourceJsonUrl}`), 'utf8'));
  const downloadItems = importScene(download.items);
  assert.equal(downloadItems.length, 1);
  assert.equal(downloadItems[0].partCatalogRef?.catalogItemId, entry.catalogItemId);
  assertCatalogIdentity(downloadItems);
  assert.equal(getStoolAccessoryGeometrySignature(downloadItems[0].sourceMesh!), entry.geometrySignature);
  saveDraft(downloadItems);
}

// Existing stool instances use the same exact catalog geometry (8 decorative
// inserts, 4 casters, 1 handle). Normalization retains the designed poses,
// including the deliberate measured handle mounting-face correction.
const asset = JSON.parse(readFileSync(path.resolve('public/models/stool/source-v1.json'), 'utf8')) as StoolSourceAsset;
const source = buildStoolSourceTemplateFromAsset(STOOL_BASELINE, asset);
const generated = buildStoolTemplateFromAsset(STOOL_BASELINE, asset);
const stool = importScene(generated.items);
const originalAccessories = catalogItems(stool);
assert.equal(originalAccessories.length, 13);
for (const item of originalAccessories) {
  const original = source.items.find(candidate => candidate.id === item.id)!;
  assert.ok(original.sourceMesh);
  assert.equal(item.sourceMesh!.positionsMm, original.sourceMesh.positionsMm);
  assert.equal(item.sourceMesh!.indices, original.sourceMesh.indices);
  assert.equal(item.sourceMesh!.materials, original.sourceMesh.materials);
  assert.equal(item.sourceMesh!.source.instancePath, original.sourceMesh.source.instancePath);
  assert.deepEqual(item.position, generated.items.find(candidate => candidate.id === item.id)!.position);
  if (item.sourceMesh!.source.semanticType !== 'stool_accessory:stainless_handle_126') {
    assert.deepEqual(item.position, original.position);
  } else {
    assert.notDeepEqual(item.position, original.position, 'The source handle gap is intentionally corrected before insertion');
  }
  assert.deepEqual(item.rotation, original.rotation);
}
assert.deepEqual(STOOL_ACCESSORY_CATALOG.map(entry => originalAccessories.filter(item => item.partCatalogRef?.catalogItemId === entry.catalogItemId).length), [8, 1, 4]);
assertDraftList(stool, 13);

const appended = rekeyImportedDesignItems(reopened, () => 'accessory-contract-append').map(item => ({
  ...item, position: [item.position[0] + 1200, item.position[1], item.position[2]] as [number, number, number],
}));
appended.forEach((item, index) => {
  assert.notEqual(item.id, reopened[index].id);
  assert.equal(item.sourceMesh, reopened[index].sourceMesh);
  assert.deepEqual(item.partCatalogRef, reopened[index].partCatalogRef, 'Append remaps scene IDs but never catalog IDs');
});
const combined = importScene([...stool, ...appended]);
assert.equal(new Set(combined.map(item => item.id)).size, combined.length);
assertDraftList(combined, 16);
const combinedDocument = saveDraft(combined);
const combinedReopened = importScene(JSON.parse(JSON.stringify(combinedDocument)).items);
assertDraftList(combinedReopened, 16);
saveDraft(combinedReopened);
for (const item of catalogItems(combinedReopened)) {
  const before = combined.find(candidate => candidate.id === item.id)!;
  assert.deepEqual(item.partCatalogRef, before.partCatalogRef);
  assert.deepEqual(item.sourceMesh, before.sourceMesh);
  assert.deepEqual(item.position, before.position);
  assert.deepEqual(item.rotation, before.rotation);
}

// A pasted reference alone cannot promote unrelated source geometry. The real
// normalize path removes legacy price/SKU fields and derives identity afresh.
const canonicalized = normalizeDesignItems([{ ...loaded[0], accessoryPrice: 123,
  catalogItemId: 'stale-procurement-sku', fastenerCatalogId: 'stale-fastener',
  partCatalogRef: loaded[1].partCatalogRef }]);
assert.equal(canonicalized[0].partCatalogRef?.catalogItemId, loaded[0].partCatalogRef.catalogItemId);
assert.equal(canonicalized[0].catalogItemId, undefined);
assert.equal(canonicalized[0].fastenerCatalogId, undefined);
assertPriceFree(canonicalized, 'canonicalizedImport');
const unknown = normalizeDesignItems([{ ...loaded[0], sourceMesh: { ...loaded[0].sourceMesh!,
  source: { ...loaded[0].sourceMesh!.source, fileSha256: '0'.repeat(64) } } }]);
assert.equal(unknown[0].partCatalogRef, undefined, 'A stale catalog reference cannot survive unknown source provenance');
assert.ok(buildMaterialList(buildProductionData(unknown, 'cn')).sections.flatMap(section => section.rows)
  .every(row => row.state === 'design_only' && !row.catalogItemId));
saveDraft(unknown);

const output = path.resolve('outputs/stool-product-20260930/stool-accessory-contract-report.json');
mkdirSync(path.dirname(output), { recursive: true });
writeFileSync(output, JSON.stringify({
  status: 'passed', verificationMode: 'designer-data-contract', browserVerified: false,
  standaloneAccessories: inserted.length, reusedStoolAccessories: originalAccessories.length,
  accessoriesAfterAppendAndReopen: catalogItems(combinedReopened).length,
  identities: STOOL_ACCESSORY_CATALOG.map(entry => entry.catalogItemId),
  materialState: 'design_only', manufacturingStatus: 'requires_acknowledgement', priceFieldsPresent: false,
  checks: ['palette loader → normalize → synchronize', 'individual downloaded JSON reopen',
    '13 original meshes and designed poses retained, including measured handle alignment', 'material-list identities and quantities',
    'editable document → JSON reopen → append → save → reopen',
    'stale identity re-derived; unknown provenance clears identity', 'legacy prices stripped; no procurement SKU inferred'],
}, null, 2));
console.log(`Stool accessory designer contract passed: 3 standalone, 13 reused, 16 after append/reopen; design-only and price-free. Report: ${output}`);
}

main().catch(error => { console.error(error); process.exitCode = 1; });
