import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {
  buildDesignDocument,
  buildProductionData,
  inspectDesignerManufacturingPrecheck,
  normalizeDesignItems,
  synchronizeDesignerSceneItems,
} from '../components/DIYDesigner';
import { createDesignSourceInfo } from '../utils/designSource';
import { inspectDesignerImportItems } from '../utils/designerImportPreflight';
import { rekeyImportedDesignItems } from '../utils/designerImportRemap';
import { buildMaterialList } from '../utils/materialList';
import { resolveStoolAccessoryReference } from '../utils/stoolAccessoryAssets';
import {
  buildStoolSourceTemplateFromAsset as buildStoolTemplateFromAsset,
  STOOL_BASELINE,
  type StoolSourceAsset,
} from '../utils/parametricStool';

const assetPath = path.resolve(process.argv[2] || 'public/models/stool/source-v1.json');
const asset = JSON.parse(fs.readFileSync(assetPath, 'utf8')) as StoolSourceAsset;
const payload = buildStoolTemplateFromAsset(STOOL_BASELINE, asset);
assert.equal(payload.source, 'parametric_stool');
assert.equal(payload.items.length, 103);
assert.ok(payload.items.every((item) => item.id.startsWith('parametric-stool-')));
const preflight = inspectDesignerImportItems(payload.items);
assert.equal(preflight.valid, true, JSON.stringify(preflight.issues));

const normalized = normalizeDesignItems(payload.items);
const items = synchronizeDesignerSceneItems(normalized);
const machiningCounts = (scene: typeof items) => scene.reduce((counts, item) => ({
  holes: counts.holes + (item.kind === 'profile' ? item.holes?.length || 0 : 0),
  tappedEnds: counts.tappedEnds + Number(Boolean(item.tappingLeft)) + Number(Boolean(item.tappingRight)),
}), { holes: 0, tappedEnds: 0 });
assert.deepEqual(machiningCounts(items), { holes: 20, tappedEnds: 24 });
items.filter((item) => item.kind === 'profile').forEach((item) => {
  const original = payload.items.find((part) => part.id === item.id)!;
  assert.deepEqual(item.holes, original.holes?.map(hole => ({ ...hole, positionMm: Math.round(hole.positionMm) })), 'Source holes survive normalization and synchronization');
  assert.equal(item.tappingLeft, original.tappingLeft);
  assert.equal(item.tappingRight, original.tappingRight);
});
assert.equal(items.length, payload.items.length, 'Import cannot infer additional stool hardware');
assert.equal(items.some((item) => item.kind === 'screw'), false, 'Source hardware must not become inferred catalog screws');
const sources = items.filter((item) => item.kind === 'imported_component');
assert.equal(sources.length, 69);
for (const item of sources) {
  const original = payload.items.find((part) => part.id === item.id)!;
  assert.equal(item.sourceMesh, original.sourceMesh, 'Normalization and synchronization retain immutable source mesh data');
  assert.deepEqual(item.position, original.position);
  assert.deepEqual(item.rotation, original.rotation);
  assert.equal(item.quantity, 1);
  assert.equal(item.autoGenerated, false);
  assert.equal(item.catalogItemId, undefined);
  assert.deepEqual(item.partCatalogRef, resolveStoolAccessoryReference(item.sourceMesh!));
  assert.equal(item.fastenerCatalogId, undefined);
  assert.equal(item.attachmentKey, undefined);
  assert.equal(item.attachedProfileIds, undefined);
}

const source = createDesignSourceInfo('parametric_template', { modelName: '复古边几凳（SU参数化草案）' });
const assertBlocked = (scene: typeof items, sourceMeshesExpected: boolean) => {
  const precheck = inspectDesignerManufacturingPrecheck(scene);
  assert.equal(precheck.applies, true);
  assert.equal(precheck.valid, false);
  assert.ok(precheck.scopes.includes('parametric_stool_draft'));
  assert.equal(precheck.scopes.includes('source_mesh_draft'), sourceMeshesExpected);
  const document = buildDesignDocument(scene, 'cn', source);
  assert.ok('productionRelease' in document);
  assert.equal(document.productionRelease.status, 'blocked');
  assert.equal('production' in document, false, 'Editable stool JSON must not contain an unreleased production projection');
  return document;
};
assertBlocked(items, true);

const materialList = buildMaterialList(buildProductionData(items, 'cn'));
const sourceRows = materialList.sections.flatMap((section) => section.rows)
  .filter((row) => row.partIds.some((id) => sources.some((item) => item.id === id)));
assert.equal(sourceRows.reduce((count, row) => count + row.quantity, 0), 69);
assert.ok(sourceRows.every((row) => row.state === 'design_only'),
  'Independent source-library identity does not release hardware for production');
assert.equal(sources.filter(item => item.partCatalogRef).length, 13,
  'Eight decorative inserts, four wheels and one handle have standalone design-library identity');

const appended = rekeyImportedDesignItems(items, () => 'stool-contract-append');
assert.ok(appended.every((item, index) => item.id.startsWith('parametric-stool-') && item.id !== items[index].id));
assert.equal(new Set([...items, ...appended].map((item) => item.id)).size, items.length * 2);
appended.forEach((item, index) => {
  assert.deepEqual(item.position, items[index].position);
  assert.deepEqual(item.rotation, items[index].rotation);
  if (item.sourceMesh) assert.equal(item.sourceMesh, items[index].sourceMesh);
});
// Offset the entire appended assembly, as the import workflow may do, without
// altering any fixed source component's mesh or local pose relative to it.
const combined = [...items, ...appended.map((item) => ({
  ...item, position: [item.position[0] + 1200, item.position[1], item.position[2]] as [number, number, number],
}))];
const saved = assertBlocked(combined, true);
const reopened = synchronizeDesignerSceneItems(normalizeDesignItems(JSON.parse(JSON.stringify(saved)).items));
assert.equal(reopened.length, 206);
assert.deepEqual(machiningCounts(reopened), { holes: 40, tappedEnds: 48 });
assert.equal(inspectDesignerImportItems(reopened).valid, true);
assertBlocked(reopened, true);
reopened.forEach((item, index) => {
  assert.equal(item.id, combined[index].id);
  assert.deepEqual(item.position, combined[index].position);
  assert.deepEqual(item.rotation, combined[index].rotation);
  if (item.kind === 'profile') {
    assert.deepEqual(item.holes, combined[index].holes, 'Save/reopen retains source hole machining and appended references');
    assert.equal(item.tappingLeft, combined[index].tappingLeft);
    assert.equal(item.tappingRight, combined[index].tappingRight);
  }
  if (item.sourceMesh) assert.deepEqual(item.sourceMesh, combined[index].sourceMesh,
    'Save/reopen retains vertices, material, texture, source path and provenance');
});

// Deleting every source mesh must not accidentally release the remaining
// structure. Appending and saving retain this independent product draft hold.
const nativeOnly = items.filter((item) => item.kind !== 'imported_component');
assert.equal(nativeOnly.length, 34);
assertBlocked(nativeOnly, false);
const nativeAppended = normalizeDesignItems(rekeyImportedDesignItems(nativeOnly, () => 'native-stool-append'));
const nativeDocument = assertBlocked(nativeAppended, false);
assertBlocked(normalizeDesignItems(JSON.parse(JSON.stringify(nativeDocument)).items), false);

const resizedPayload = buildStoolTemplateFromAsset({ widthMm: 450, depthMm: 520, heightMm: 650 }, asset);
const resizedItems = synchronizeDesignerSceneItems(normalizeDesignItems(resizedPayload.items));
const resizedDocument = assertBlocked(resizedItems, true);
const resizedReopened = synchronizeDesignerSceneItems(normalizeDesignItems(JSON.parse(JSON.stringify(resizedDocument)).items));
assert.deepEqual(machiningCounts(resizedReopened), { holes: 20, tappedEnds: 24 });
resizedReopened.filter((item) => item.kind === 'profile').forEach((item) => {
  const original = resizedPayload.items.find((part) => part.id === item.id)!;
  assert.deepEqual(item.holes, original.holes?.map(hole => ({ ...hole, positionMm: Math.round(hole.positionMm) })), 'Resized source hole metadata survives with whole-millimetre stations');
  assert.equal(item.tappingLeft, original.tappingLeft);
  assert.equal(item.tappingRight, original.tappingRight);
});

console.log('Stool source geometry, material list, manufacturing hold, append and editable JSON contract passed.');
