import {
  DISPLAY_RACK_3_BASELINE,
  DISPLAY_RACK_3_LIMITS,
  buildDisplayRack3Template,
} from '../utils/parametricDisplayRack';
import {
  completeDisplayRackConnectionSystem,
  inspectDisplayRackConnectionCandidates,
  normalizeDesignItems,
} from '../components/DIYDesigner';

const cases = [
  DISPLAY_RACK_3_BASELINE,
  {
    ...DISPLAY_RACK_3_BASELINE,
    widthMm: DISPLAY_RACK_3_LIMITS.widthMm.min,
    heightMm: DISPLAY_RACK_3_LIMITS.heightMm.min,
    depthMm: DISPLAY_RACK_3_LIMITS.depthMm.min,
    baseCabinetHeightMm: DISPLAY_RACK_3_LIMITS.baseCabinetHeightMm.min,
    upperLevels: DISPLAY_RACK_3_LIMITS.upperLevels.min,
    lowerLevels: DISPLAY_RACK_3_LIMITS.lowerLevels.min,
  },
  {
    ...DISPLAY_RACK_3_BASELINE,
    widthMm: DISPLAY_RACK_3_LIMITS.widthMm.max,
    heightMm: DISPLAY_RACK_3_LIMITS.heightMm.max,
    depthMm: DISPLAY_RACK_3_LIMITS.depthMm.max,
    baseCabinetHeightMm: DISPLAY_RACK_3_BASELINE.baseCabinetHeightMm,
    upperLevels: DISPLAY_RACK_3_LIMITS.upperLevels.max,
    lowerLevels: DISPLAY_RACK_3_LIMITS.lowerLevels.max,
  },
  {
    ...DISPLAY_RACK_3_BASELINE,
    heightMm: 2000,
    baseCabinetHeightMm: 850,
    upperLevels: 3,
    lowerLevels: 5,
  },
];

cases.forEach((parameters, index) => {
  const payload = buildDisplayRack3Template(parameters);
  const normalized = normalizeDesignItems(payload.items as never);
  const { items, check } = completeDisplayRackConnectionSystem(normalized);
  const connectorCount = items.filter((item) => item.kind === 'connector' && item.autoGenerated).length;
  const directHoleCount = items.reduce((count, item) => (
    count + (item.holes || []).filter((hole) => hole.jointKey?.endsWith(':DRILL-TAP')).length
  ), 0);
  console.log(JSON.stringify({ case: index + 1, valid: check.valid, connectorCount, directHoleCount, issues: check.issues }));
  if (!check.valid) {
    const missingKeys = new Set(check.issues.filter((issue) => issue.includes('当前为0个直锁＋0个角码')).map((issue) => issue.split('应且只能')[0]));
    console.log(JSON.stringify(inspectDisplayRackConnectionCandidates(normalized).filter((row) => missingKeys.has(row.jointKey))));
    const missingIds = new Set(Array.from(missingKeys).flatMap((key) => key.split(':JOINT:')));
    console.log(JSON.stringify(normalized.filter((item) => missingIds.has(item.id)).map((item) => ({
      id: item.id,
      name: item.name,
      position: item.position,
      rotation: item.rotation,
      length: item.length,
    }))));
  }
  if (!check.valid) process.exitCode = 1;
});
